import { getSupabaseServiceClient } from "@/lib/auth/session";
import { getPlan } from "@/lib/billing";
import type { AdminActor, AuditInput } from "./types";

export class OperationsRepository{
  constructor(private readonly client:any=getSupabaseServiceClient()){}
  async audit(actor:AdminActor,input:AuditInput){const result=await this.client.from("admin_audit_logs").insert({actor_user_id:actor.userId,actor_role:actor.role,action:input.action,target_type:input.targetType,target_id:input.targetId,before_state:input.before??null,after_state:input.after??null,reason:requiredReason(input.reason),correlation_id:actor.correlationId});check(result,"Unable to record the required admin audit event.");}
  async source(id:string){const result=await this.client.from("sources").select("*").eq("id",id).maybeSingle();check(result,"Unable to load source.");return result.data??null;}
  async dashboard(){const [profiles,subscriptions,credits,sources,scans,listings,flags,ai,billing,errors,support,audit,featureFlags,deadLetters,failedUrls]=await Promise.all([
    this.client.from("profiles").select("id,email,display_name,platform_role,account_disabled_at,created_at,updated_at,subscriptions(plan_key,status,current_period_end)").order("created_at",{ascending:false}).limit(200),
    this.client.from("subscriptions").select("plan_key,status"),
    this.client.from("credit_ledger").select("id,user_id,amount,entry_type,reason_code,source_reference,created_at").order("created_at",{ascending:false}).limit(500),
    this.client.from("sources").select("*").order("name"),
    this.client.from("source_scan_jobs").select("*,sources(name)").order("created_at",{ascending:false}).limit(100),
    this.client.from("sweepstakes").select("id,title,sponsor_name,status,source_confidence_score,legitimacy_score,end_at,updated_at,listing_quality_flags(id,flag_type,severity,status)").order("updated_at",{ascending:false}).limit(200),
    this.client.from("listing_quality_flags").select("id,sweepstakes_id,flag_type,severity,status,details,created_at").in("status",["open","reviewing"]).order("created_at",{ascending:false}).limit(100),
    this.client.from("ai_enrichment_runs").select("status,input_tokens,output_tokens,estimated_cost_usd,error_code,started_at").gte("started_at",monthStart()).limit(1000),
    this.client.from("billing_events").select("provider_event_id,event_type,status,error_message,received_at").in("status",["failed","processing"]).order("received_at",{ascending:false}).limit(100),
    this.client.from("application_errors").select("*").order("occurred_at",{ascending:false}).limit(50),
    this.client.from("support_requests").select("*").in("status",["open","reviewing"]).order("created_at",{ascending:false}).limit(100),
    this.client.from("admin_audit_logs").select("*").order("created_at",{ascending:false}).limit(100),
    this.client.from("feature_flags").select("*").order("key"),
    this.client.from("source_scan_jobs").select("*,sources(name)").eq("status","dead_letter").order("created_at",{ascending:false}).limit(100),
    this.client.from("discovered_urls").select("*,sources(name)").eq("status","failed").order("updated_at",{ascending:false}).limit(100)
  ]);for(const [result,label] of [[profiles,"users"],[subscriptions,"subscriptions"],[credits,"credit usage"],[sources,"sources"],[scans,"scan jobs"],[listings,"listings"],[flags,"listing reviews"],[ai,"AI usage"],[billing,"billing failures"],[errors,"application errors"],[support,"support requests"],[audit,"audit log"],[featureFlags,"feature flags"],[deadLetters,"dead letters"],[failedUrls,"failed URLs"]] as const)check(result,`Unable to load ${label}.`);
    const userRows=profiles.data??[],subRows=subscriptions.data??[],creditRows=credits.data??[],sourceRows=sources.data??[],scanRows=scans.data??[],listingRows=listings.data??[],flagRows=flags.data??[],aiRows=ai.data??[],billingRows=billing.data??[];
    const paid=subRows.filter((x:any)=>["active","trialing","past_due"].includes(x.status)&&x.plan_key!=="free_flight");
    const metrics={activeUsers:userRows.filter((x:any)=>!x.account_disabled_at).length,paidSubscribers:paid.length,mrrCents:paid.reduce((sum:number,x:any)=>sum+getPlan(x.plan_key).monthlyPriceCents,0),aiRuns:aiRows.length,aiTokens:aiRows.reduce((sum:number,x:any)=>sum+Number(x.input_tokens||0)+Number(x.output_tokens||0),0),aiCostUsd:aiRows.reduce((sum:number,x:any)=>sum+Number(x.estimated_cost_usd||0),0),pilotCreditsConsumed:Math.abs(creditRows.filter((x:any)=>x.entry_type==="consume"&&x.created_at>=monthStart()).reduce((sum:number,x:any)=>sum+Number(x.amount||0),0)),activeSources:sourceRows.filter((x:any)=>x.scan_enabled).length,failedScans:scanRows.filter((x:any)=>["failed","dead_letter"].includes(x.status)).length,listingsDiscovered:listingRows.length,pendingReview:flagRows.length,duplicateCandidates:flagRows.filter((x:any)=>String(x.flag_type).includes("duplicate")).length,highRiskListings:listingRows.filter((x:any)=>Number(x.legitimacy_score)<40||x.listing_quality_flags?.some((f:any)=>f.severity==="critical"&&f.status==="open")).length,webhookFailures:billingRows.filter((x:any)=>x.status==="failed").length,queueFailures:scanRows.filter((x:any)=>["failed","dead_letter"].includes(x.status)).length,recentApplicationErrors:(errors.data??[]).length};
    const sourceFailureRates=sourceRows.map((source:any)=>{const jobs=scanRows.filter((job:any)=>job.source_id===source.id);const failures=jobs.filter((job:any)=>["failed","dead_letter"].includes(job.status)).length;return{sourceId:source.id,sampleSize:jobs.length,failures,rate:jobs.length?failures/jobs.length:0};});
    return{metrics,health:{scanner:health(metrics.failedScans,metrics.activeSources>0),aiProvider:health(aiRows.filter((x:any)=>x.status==="failed").length,Boolean(process.env.OPENAI_API_KEY)),emailProvider:health(0,process.env.PLAYPACKPILOT_EMAIL_ENABLED==="true"&&process.env.EMAIL_PROVIDER==="resend"),stripeWebhook:health(metrics.webhookFailures,Boolean(process.env.STRIPE_SECRET_KEY)),queue:health(metrics.queueFailures,true)},users:userRows,creditLedger:creditRows,sources:sourceRows,sourceFailureRates,scanJobs:scanRows,listings:listingRows,reviewFlags:flagRows,billingFailures:billingRows,applicationErrors:errors.data??[],supportRequests:support.data??[],auditLogs:audit.data??[],featureFlags:featureFlags.data??[],deadLetters:deadLetters.data??[],failedUrls:failedUrls.data??[]};
  }
  async listing(id:string){const [listing,evidence,rules,changes,merges]=await Promise.all([
    this.client.from("sweepstakes").select("*,sweepstakes_prizes(*),sweepstakes_eligibility(*),sweepstakes_entry_methods(*),listing_quality_flags(*)").eq("id",id).maybeSingle(),
    this.client.from("sweepstakes_field_evidence").select("*").eq("sweepstakes_id",id).order("extracted_at",{ascending:false}),
    this.client.from("sweepstakes_rules_versions").select("*").eq("sweepstakes_id",id).order("fetched_at",{ascending:false}),
    this.client.from("sweepstakes_change_events").select("*").eq("sweepstakes_id",id).order("detected_at",{ascending:false}),
    this.client.from("sweepstakes_merge_events").select("*").or(`target_sweepstakes_id.eq.${id},source_sweepstakes_id.eq.${id}`).order("created_at",{ascending:false})
  ]);for(const [result,label] of [[listing,"listing review"],[evidence,"field evidence"],[rules,"rules history"],[changes,"change history"],[merges,"merge history"]] as const)check(result,`Unable to load ${label}.`);return listing.data?{...listing.data,sweepstakes_field_evidence:evidence.data??[],sweepstakes_rules_versions:rules.data??[],sweepstakes_change_events:changes.data??[],sweepstakes_merge_events:merges.data??[]}:null;}
  async updateListing(id:string,patch:Record<string,unknown>){const result=await this.client.from("sweepstakes").update({...patch,updated_at:new Date().toISOString()}).eq("id",id).select("*").maybeSingle();check(result,"Unable to correct listing.");if(!result.data)throw new Error("Listing was not found.");return result.data;}
  async resolveFlags(id:string){const result=await this.client.from("listing_quality_flags").update({status:"resolved",resolved_at:new Date().toISOString()}).eq("sweepstakes_id",id).in("status",["open","reviewing"]);check(result,"Unable to resolve listing flags.");}
  async addFlag(id:string,type:string,severity:string,details:Record<string,unknown>){const result=await this.client.from("listing_quality_flags").insert({sweepstakes_id:id,flag_type:type,severity,details,status:"open"}).select("*").single();check(result,"Unable to flag listing.");return result.data;}
  async merge(targetId:string,sourceId:string,actorId:string,reason:string){const result=await this.client.rpc("admin_merge_sweepstakes",{p_target_id:targetId,p_source_id:sourceId,p_actor_id:actorId,p_reason:reason});check(result,"Unable to merge listings.");return String(result.data);}
  async undoMerge(id:string,actorId:string){const result=await this.client.rpc("admin_undo_merge",{p_event_id:id,p_actor_id:actorId});check(result,"Unable to undo merge.");return String(result.data);}
  async user(id:string){const [profile,ledger,events]=await Promise.all([this.client.from("profiles").select("*,subscriptions(*),entitlements(*)").eq("id",id).maybeSingle(),this.client.from("credit_ledger").select("*").eq("user_id",id).order("created_at",{ascending:false}).limit(100),this.client.from("billing_events").select("*").eq("user_id",id).order("received_at",{ascending:false}).limit(100)]);check(profile,"Unable to load user.");check(ledger,"Unable to load credit ledger.");check(events,"Unable to load billing events.");return{profile:profile.data,creditLedger:ledger.data??[],billingEvents:events.data??[]};}
  async adjustCredits(userId:string,amount:number,reason:string,key:string,actorId:string){const result=await this.client.rpc("adjust_pilot_credits",{p_user_id:userId,p_amount:amount,p_reason_code:amount>0?"admin_promotional_credit":"admin_credit_correction",p_source_reference:actorId,p_idempotency_key:key,p_metadata:{reason,actorId}});check(result,"Unable to adjust Pilot Credits.");return Array.isArray(result.data)?result.data[0]:result.data;}
  async disableUser(id:string,disabled:boolean){const result=await this.client.from("profiles").update({account_disabled_at:disabled?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq("id",id).select("id,email,account_disabled_at").maybeSingle();check(result,"Unable to update account access.");if(!result.data)throw new Error("User was not found.");return result.data;}
  async updateSupport(id:string,input:Record<string,unknown>,actorId:string){const status=String(input.status??"reviewing");if(!["reviewing","resolved","closed"].includes(status))throw new Error("Invalid support status.");const result=await this.client.from("support_requests").update({status,priority:parsePriority(input.priority),assigned_to:actorId,resolution:text(input.resolution,2000)||null,updated_at:new Date().toISOString()}).eq("id",id).select("*").maybeSingle();check(result,"Unable to update support request.");if(!result.data)throw new Error("Support request was not found.");return result.data;}
  async setFlag(key:string,input:Record<string,unknown>,actorId:string){if(!/^[a-z][a-z0-9_.-]{2,79}$/.test(key))throw new Error("Invalid feature flag key.");const result=await this.client.from("feature_flags").upsert({key,enabled:input.enabled===true,description:text(input.description,500),metadata:object(input.metadata),updated_by:actorId,updated_at:new Date().toISOString()},{onConflict:"key"}).select("*").single();check(result,"Unable to update feature flag.");return result.data;}
  async retryDeadLetter(id:string){const result=await this.client.from("source_scan_jobs").update({status:"queued",error_summary:null,completed_at:null}).eq("id",id).eq("status","dead_letter").select("*").maybeSingle();check(result,"Unable to retry dead-letter job.");if(!result.data)throw new Error("Dead-letter job was not found.");return result.data;}
  async recordError(input:{correlationId:string;route:string;method:string;errorName:string;safeMessage:string}){try{await this.client.from("application_errors").insert({correlation_id:input.correlationId,route:input.route,method:input.method,error_name:input.errorName,safe_message:input.safeMessage});}catch{/* Error retention must never replace the original response path. */}}
}
function check(result:any,message:string){if(result?.error)throw new Error(`${message} ${result.error.message??""}`.trim());}
function monthStart(){const now=new Date();return new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1)).toISOString();}
function health(failures:number,configured:boolean){return{status:!configured?"disabled":failures>0?"degraded":"healthy",failures,configured};}
function requiredReason(value:unknown){const out=text(value,1000);if(out.length<3)throw new Error("A reason of at least 3 characters is required.");return out;}
function text(value:unknown,max:number){return typeof value==="string"?value.trim().slice(0,max):"";}
function object(value:unknown){return value&&typeof value==="object"&&!Array.isArray(value)?value:{};}
function parsePriority(value:unknown){const out=String(value??"normal");if(!["low","normal","high","urgent"].includes(out))throw new Error("Invalid support priority.");return out;}
