import { randomUUID } from "node:crypto";
import { safePublicUrl } from "@/lib/scanner/fetcher";
import type { AdminActor } from "./types";
import { OperationsRepository } from "./repository";

const textFields=new Set(["title","sponsor_name","summary","timezone"]);
const urlFields=new Set(["official_url","rules_url"]);
const numberFields=new Set(["estimated_total_prize_value","entry_effort_score","legitimacy_score","source_confidence_score"]);
const dateFields=new Set(["start_at","end_at"]);
const scoreFields=new Set(["entry_effort_score","legitimacy_score","source_confidence_score"]);
const entryFrequencies=new Set(["one_time","daily","weekly","monthly","unlimited","unknown"]);
export function actor(session:any,request:any):AdminActor{return{...session,correlationId:String(request.id??request.headers?.["x-request-id"]??`admin_${randomUUID()}`)};}
export function adminReason(value:unknown){const result=typeof value==="string"?value.trim().slice(0,1000):"";if(result.length<3)throw new Error("An administrative reason of at least 3 characters is required.");return result;}
export async function correctListing(admin:AdminActor,id:string,input:Record<string,unknown>,repo=new OperationsRepository()){const reason=adminReason(input.reason),before=await repo.listing(id);if(!before)throw new Error("Listing was not found.");const patch:Record<string,unknown>={};for(const [key,value] of Object.entries(input.fields&&typeof input.fields==="object"?input.fields as Record<string,unknown>:{})){if(textFields.has(key))patch[key]=String(value??"").trim().slice(0,5000);else if(key==="currency"){const currency=String(value??"").trim().toUpperCase();if(!/^[A-Z]{3}$/.test(currency))throw new Error("Invalid currency.");patch[key]=currency;}else if(key==="entry_frequency"){const frequency=String(value??"");if(!entryFrequencies.has(frequency))throw new Error("Invalid entry_frequency.");patch[key]=frequency;}else if(urlFields.has(key))patch[key]=value?safePublicUrl(String(value)).toString():null;else if(numberFields.has(key)){const number=Number(value);if(!Number.isFinite(number)||number<0||scoreFields.has(key)&&number>100)throw new Error(`Invalid ${key}.`);patch[key]=number;}else if(dateFields.has(key))patch[key]=value?new Date(String(value)).toISOString():null;}if(!Object.keys(patch).length)throw new Error("No allowlisted listing corrections were supplied.");const after=await repo.updateListing(id,patch);await repo.audit(admin,{action:"listing.corrected",targetType:"sweepstakes",targetId:id,before,after,reason});return after;}
export async function decideListing(admin:AdminActor,id:string,input:Record<string,unknown>,repo=new OperationsRepository()){const decision=String(input.decision??""),reason=adminReason(input.reason),before=await repo.listing(id);if(!before)throw new Error("Listing was not found.");let after;if(decision==="approve"){after=await repo.updateListing(id,{status:"active"});await repo.resolveFlags(id);}else if(decision==="reject")after=await repo.updateListing(id,{status:"unverifiable"});else if(decision==="suspicious"){await repo.addFlag(id,"administrator_suspicious","critical",{reason});after=await repo.updateListing(id,{status:"unverifiable"});}else if(decision==="expired"||decision==="canceled")after=await repo.updateListing(id,{status:decision});else throw new Error("Invalid listing decision.");await repo.audit(admin,{action:`listing.${decision}`,targetType:"sweepstakes",targetId:id,before,after,reason});return after;}
export async function mergeListings(admin:AdminActor,input:Record<string,unknown>,repo=new OperationsRepository()){const targetId=String(input.targetId??""),sourceId=String(input.sourceId??""),reason=adminReason(input.reason);const eventId=await repo.merge(targetId,sourceId,admin.userId,reason);await repo.audit(admin,{action:"listing.merged",targetType:"sweepstakes_merge",targetId:eventId,before:{targetId,sourceId},after:{status:"applied"},reason});return{eventId,targetId,sourceId,status:"applied"};}
export async function undoMerge(admin:AdminActor,id:string,input:Record<string,unknown>,repo=new OperationsRepository()){const reason=adminReason(input.reason),targetId=await repo.undoMerge(id,admin.userId);await repo.audit(admin,{action:"listing.merge_undone",targetType:"sweepstakes_merge",targetId:id,before:{status:"applied"},after:{status:"undone",targetId},reason});return{id,targetId,status:"undone"};}
export async function adjustCredits(admin:AdminActor,userId:string,input:Record<string,unknown>,repo=new OperationsRepository()){const amount=Number(input.amount),reason=adminReason(input.reason);if(!Number.isInteger(amount)||amount===0||Math.abs(amount)>100000)throw new Error("Credit adjustment must be a non-zero integer no greater than 100000.");const key=`admin-credit:${userId}:${String(input.idempotencyKey??randomUUID()).replace(/[^a-zA-Z0-9._:-]/g,"-").slice(0,120)}`;const result=await repo.adjustCredits(userId,amount,reason,key,admin.userId);await repo.audit(admin,{action:amount>0?"billing.promotional_credit_granted":"billing.credit_corrected",targetType:"profile",targetId:userId,after:{amount,result,key},reason});return result;}
