import { getSupabaseServiceClient } from "@/lib/auth/session";
import type { CustomScanFilters, CustomScanner, DigestKind, NotificationPreferences } from "./types";
import { isDigestDue } from "./schedule";

export class AlertsRepository{
  constructor(private readonly client:any=getSupabaseServiceClient()){}
  async summary(userId:string){const [notifications,preferences,scanners,runs,sources]=await Promise.all([this.client.from("notifications").select("*").eq("user_id",userId).order("created_at",{ascending:false}).limit(100),this.client.from("notification_preferences").select("*").eq("user_id",userId).maybeSingle(),this.client.from("custom_scanners").select("*").eq("user_id",userId).order("created_at"),this.client.from("custom_scan_runs").select("*").eq("user_id",userId).order("created_at",{ascending:false}).limit(50),this.approvedSources()]);check(notifications,"Unable to load alerts.");check(preferences,"Unable to load notification preferences.");check(scanners,"Unable to load custom scanners.");check(runs,"Unable to load custom scan history.");const items=notifications.data??[];return{notifications:items,unreadCount:items.filter((x:any)=>!x.read_at).length,preferences:mapPreferences(preferences.data),customScanners:scanners.data??[],customScanRuns:runs.data??[],approvedSources:sources,emailProvider:process.env.EMAIL_PROVIDER==="resend"&&process.env.PLAYPACKPILOT_EMAIL_ENABLED==="true"?"resend":"disabled"};}
  async savePreferences(userId:string,input:NotificationPreferences){const payload={user_id:userId,in_app_enabled:input.inAppEnabled,email_enabled:input.emailEnabled,daily_digest_enabled:input.dailyDigestEnabled,weekly_digest_enabled:input.weeklyDigestEnabled,ending_soon_enabled:input.endingSoonEnabled,high_value_enabled:input.highValueEnabled,recommendations_enabled:input.recommendationsEnabled,entry_reminders_enabled:input.entryRemindersEnabled,email_unsubscribed_at:input.emailEnabled?null:new Date().toISOString(),updated_at:new Date().toISOString()};const result=await this.client.from("notification_preferences").upsert(payload,{onConflict:"user_id"}).select("*").single();check(result,"Unable to save notification preferences.");return mapPreferences(result.data);}
  async markRead(userId:string,id?:string){let query=this.client.from("notifications").update({read_at:new Date().toISOString()}).eq("user_id",userId);if(id)query=query.eq("id",id);else query=query.is("read_at",null);const result=await query;check(result,"Unable to mark alerts read.");return{updated:true};}
  async approvedSources(ids?:string[]){let query=this.client.from("sources").select("id,name,base_url,attribution_text").eq("scan_enabled",true).eq("robots_policy_status","approved").eq("terms_review_status","approved").order("name");if(ids?.length)query=query.in("id",ids);const result=await query;check(result,"Unable to load approved sources.");return result.data??[];}
  async countScanners(userId:string){const result=await this.client.from("custom_scanners").select("id",{count:"exact",head:true}).eq("user_id",userId);check(result,"Unable to count custom scanners.");return Number(result.count??0);}
  async countMonthlyRuns(userId:string,now=new Date()){const start=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1)).toISOString();const result=await this.client.from("custom_scan_runs").select("id",{count:"exact",head:true}).eq("user_id",userId).gte("created_at",start).in("status",["queued","running","completed","partial"]);check(result,"Unable to count monthly custom scans.");return Number(result.count??0);}
  async scanners(userId:string){const result=await this.client.from("custom_scanners").select("*").eq("user_id",userId).order("created_at");check(result,"Unable to list custom scanners.");return result.data??[] as CustomScanner[];}
  async scanner(userId:string,id:string){const result=await this.client.from("custom_scanners").select("*").eq("id",id).eq("user_id",userId).maybeSingle();check(result,"Unable to load custom scanner.");if(!result.data)throw new Error("Custom scanner was not found.");return result.data as CustomScanner;}
  async createScanner(userId:string,input:{name:string;filters:CustomScanFilters;sourceIds:string[];cadenceMinutes:number}){const now=new Date();const result=await this.client.from("custom_scanners").insert({user_id:userId,name:input.name,filters:input.filters,source_ids:input.sourceIds,cadence_minutes:input.cadenceMinutes,next_run_at:new Date(now.getTime()+input.cadenceMinutes*60000).toISOString()}).select("*").single();check(result,"Unable to create custom scanner.");return result.data;}
  async updateScanner(userId:string,id:string,input:{name:string;filters:CustomScanFilters;sourceIds:string[];cadenceMinutes:number;enabled:boolean}){const result=await this.client.from("custom_scanners").update({name:input.name,filters:input.filters,source_ids:input.sourceIds,cadence_minutes:input.cadenceMinutes,enabled:input.enabled,next_run_at:new Date(Date.now()+input.cadenceMinutes*60000).toISOString(),updated_at:new Date().toISOString()}).eq("id",id).eq("user_id",userId).select("*").maybeSingle();check(result,"Unable to update custom scanner.");if(!result.data)throw new Error("Custom scanner was not found.");return result.data;}
  async deleteScanner(userId:string,id:string){const result=await this.client.from("custom_scanners").delete().eq("id",id).eq("user_id",userId);check(result,"Unable to delete custom scanner.");return{deleted:true};}
  async createRun(scanner:CustomScanner,key:string){const result=await this.client.from("custom_scan_runs").insert({custom_scanner_id:scanner.id,user_id:scanner.user_id,status:"running",scheduled_for:new Date().toISOString(),started_at:new Date().toISOString(),source_ids:scanner.source_ids,credit_idempotency_key:key}).select("*").single();check(result,"Unable to start custom scan.");return result.data;}
  async runByCreditKey(userId:string,key:string){const result=await this.client.from("custom_scan_runs").select("*").eq("user_id",userId).eq("credit_idempotency_key",key).maybeSingle();check(result,"Unable to check custom scan idempotency.");return result.data??null;}
  async finishRun(id:string,input:{status:"completed"|"partial"|"failed";matchCount:number;summary:Record<string,unknown>;error?:string}){const result=await this.client.from("custom_scan_runs").update({status:input.status,match_count:input.matchCount,result_summary:input.summary,error_message:input.error??null,completed_at:new Date().toISOString()}).eq("id",id).select("*").single();check(result,"Unable to finalize custom scan.");return result.data;}
  async matchCount(_userId:string,filters:CustomScanFilters,sourceIds:string[]){const result=await this.client.rpc("count_custom_scan_matches",{p_filters:filters,p_source_ids:sourceIds});check(result,"Unable to evaluate custom scan matches.");return Number(result.data??0);}
  async generateNotifications(now=new Date()){const result=await this.client.rpc("generate_phase9_notifications",{p_now:now.toISOString()});check(result,"Unable to generate scheduled alerts.");return Number(result.data??0);}
  async generateHighMatches(){const profiles=await this.client.from("user_search_profiles").select("id,user_id,name,filters").eq("alert_enabled",true).limit(500);check(profiles,"Unable to load high-match profiles.");let created=0;for(const profile of profiles.data??[]){const f=profile.filters??{};const matches=await this.client.rpc("search_sweepstakes_radar",{p_user_id:profile.user_id,p_query:f.q??null,p_category:f.category??null,p_min_prize:f.minPrize??null,p_deadline_before:null,p_start_after:null,p_frequency:f.frequency??null,p_max_effort:null,p_country:null,p_region:null,p_user_age:null,p_sponsor:null,p_purchase_required:null,p_social_required:null,p_min_legitimacy:null,p_min_source_confidence:null,p_saved:null,p_entered:null,p_sort:"recommended",p_limit:5,p_offset:0});check(matches,"Unable to evaluate high-match profiles.");for(const match of matches.data??[]){if(Number(match.recommendation_score??match.match_score??0)<70)continue;const inserted=await this.client.from("notifications").insert({user_id:profile.user_id,type:"high_match",title:"New high-match opportunity",body:`${String(match.title??"A new opportunity")} matches ${profile.name}. Verify sponsor rules before entering.`,sweepstakes_id:match.id,source_reference:String(match.id),dedupe_key:`high-match:${profile.id}:${match.id}`,priority:65,metadata:{searchProfileId:profile.id,matchScore:Number(match.recommendation_score??match.match_score??0)}});if(!inserted.error)created+=1;else if(String(inserted.error.code)!=="23505")check(inserted,"Unable to create a high-match alert.");}}return created;}
  async claimDueScanners(now=new Date(),limit=10){const result=await this.client.rpc("claim_due_custom_scanners",{p_now:now.toISOString(),p_limit:limit});check(result,"Unable to claim scheduled custom scans.");return result.data??[] as CustomScanner[];}
  async digestCandidates(kind:DigestKind,now=new Date()){const daily=kind==="daily";const result=await this.client.from("profiles").select("id,email,display_name,timezone,notification_preferences(*)").limit(500);check(result,"Unable to load digest candidates.");return(result.data??[]).map((row:any)=>{const preferences=mapPreferences(Array.isArray(row.notification_preferences)?row.notification_preferences[0]:row.notification_preferences);return{...row,preferences};}).filter((row:any)=>row.preferences.emailEnabled&&!row.preferences.emailUnsubscribedAt&&(daily?row.preferences.dailyDigestEnabled:row.preferences.weeklyDigestEnabled)&&isDigestDue(row.timezone||"UTC",daily?"daily":"weekly",now));}
  async claimDigest(userId:string,kind:DigestKind,windowStart:string,windowEnd:string){const result=await this.client.from("digest_runs").insert({user_id:userId,kind,window_start:windowStart,window_end:windowEnd,status:"processing"}).select("*").maybeSingle();if(result.error&&String(result.error.code)==="23505")return null;check(result,"Unable to claim digest.");return result.data;}
  async digestItems(userId:string,windowStart:string,preferences?:NotificationPreferences){const result=await this.client.from("notifications").select("*").eq("user_id",userId).gte("created_at",windowStart).order("priority",{ascending:false}).limit(25);check(result,"Unable to load digest items.");return filterDigestItems(result.data??[],preferences??mapPreferences(null));}
  async finishDigest(id:string,status:"delivered"|"failed"|"skipped",itemCount:number,error?:string){const result=await this.client.from("digest_runs").update({status,item_count:itemCount,error_message:error??null,completed_at:new Date().toISOString()}).eq("id",id);check(result,"Unable to finalize digest.");}
}
export function mapPreferences(row:any):NotificationPreferences{return{inAppEnabled:row?.in_app_enabled??true,emailEnabled:row?.email_enabled??false,dailyDigestEnabled:row?.daily_digest_enabled??false,weeklyDigestEnabled:row?.weekly_digest_enabled??true,endingSoonEnabled:row?.ending_soon_enabled??true,highValueEnabled:row?.high_value_enabled??true,recommendationsEnabled:row?.recommendations_enabled??true,entryRemindersEnabled:row?.entry_reminders_enabled??true,emailUnsubscribedAt:row?.email_unsubscribed_at??null};}
export function filterDigestItems(items:any[],preferences:NotificationPreferences){return items.filter(item=>item.type!=="ending_soon"||preferences.endingSoonEnabled).filter(item=>item.type!=="high_match"||preferences.recommendationsEnabled||preferences.highValueEnabled).filter(item=>item.type!=="entry_due"||preferences.entryRemindersEnabled);}
function check(result:any,message:string){if(result?.error)throw new Error(`${message} ${result.error.message??""}`.trim());}
