import { randomUUID } from "node:crypto";
import { AppConfigError } from "@/lib/env";
import { BillingRepository, withPilotCredits } from "@/lib/billing";
import { SourceScanner } from "@/lib/scanner";
import { SupabaseScannerRepository } from "@/lib/scanner/repository";
import { customScanPolicy } from "./catalog";
import { configuredEmailProvider } from "./email";
import { AlertsRepository } from "./repository";
import type { CustomScanFilters, CustomScanner, DigestKind, EmailProvider, NotificationPreferences } from "./types";

export async function alertsSummary(userId:string,repo=new AlertsRepository(),billing=new BillingRepository()){const [summary,subscription,ledger]=await Promise.all([repo.summary(userId),billing.subscription(userId),billing.ledger(userId)]);const planKey=["active","trialing","past_due"].includes(subscription.status)?subscription.planKey:"free_flight";return{...summary,planKey,customScanPolicy:customScanPolicy(planKey),customScanCost:Number(process.env.PILOT_CREDIT_COST_CUSTOM_SCAN)||10,creditBalance:ledger.balance};}
export function parsePreferences(input:Record<string,unknown>):NotificationPreferences{return{inAppEnabled:input.inAppEnabled!==false,emailEnabled:input.emailEnabled===true,dailyDigestEnabled:input.dailyDigestEnabled===true,weeklyDigestEnabled:input.weeklyDigestEnabled===true,endingSoonEnabled:input.endingSoonEnabled!==false,highValueEnabled:input.highValueEnabled!==false,recommendationsEnabled:input.recommendationsEnabled!==false,entryRemindersEnabled:input.entryRemindersEnabled!==false,emailUnsubscribedAt:null};}
export async function saveAlertPreferences(userId:string,input:Record<string,unknown>,repo=new AlertsRepository()){return repo.savePreferences(userId,parsePreferences(input));}
export async function createCustomScanner(userId:string,input:Record<string,unknown>,repo=new AlertsRepository(),billing=new BillingRepository()){const {policy,parsed}=await validateScanner(userId,input,repo,billing);if(await repo.countScanners(userId)>=policy.maxProfiles)throw new AppConfigError(`Your plan allows ${policy.maxProfiles} custom scanner profiles.`);return repo.createScanner(userId,parsed);}
export async function updateCustomScanner(userId:string,id:string,input:Record<string,unknown>,repo=new AlertsRepository(),billing=new BillingRepository()){await repo.scanner(userId,id);const {parsed}=await validateScanner(userId,input,repo,billing);return repo.updateScanner(userId,id,{...parsed,enabled:input.enabled!==false});}
export async function runCustomScanner(userId:string,id:string,options:{repo?:AlertsRepository;billing?:BillingRepository;scanner?:SourceScanner;idempotencyKey?:string}={}){const repo=options.repo??new AlertsRepository(),billing=options.billing??new BillingRepository(),scanner=options.scanner??new SourceScanner(new SupabaseScannerRepository());const profile=await repo.scanner(userId,id);const subscription=await billing.subscription(userId);const planKey=["active","trialing","past_due"].includes(subscription.status)?subscription.planKey:"free_flight";const policy=customScanPolicy(planKey);if(!policy.enabled)throw new AppConfigError("Custom scanning requires Ace Pilot or Squadron.");if(await repo.countMonthlyRuns(userId)>=policy.monthlyRuns)throw new AppConfigError(`Monthly custom scan limit reached (${policy.monthlyRuns}).`);const key=options.idempotencyKey??`custom-scan:${userId}:${id}:${randomUUID()}`;const existing=await repo.runByCreditKey(userId,key);if(existing)return{value:{run:existing,matchCount:existing.match_count,sourceResults:existing.result_summary?.sources??[],duplicate:true},cost:0,balance:(await billing.ledger(userId)).balance};return withPilotCredits({userId,operation:"custom_scan",sourceReference:id,idempotencyKey:key,repository:billing,execute:async()=>{const run=await repo.createRun(profile,key);try{const results=[] as Array<Record<string,unknown>>;for(const sourceId of profile.source_ids){try{results.push(await scanner.runSource(sourceId));}catch(error){results.push({sourceId,status:"failed",error:error instanceof Error?error.message:"Scan failed"});}}const matchCount=await repo.matchCount(userId,profile.filters,profile.source_ids);const failed=results.filter(x=>x.status==="failed").length;const saved=await repo.finishRun(run.id,{status:failed===results.length?"failed":failed?"partial":"completed",matchCount,summary:{sources:results,sourceIds:profile.source_ids,filters:profile.filters}});if(failed===results.length)throw new Error("All approved sources failed during the custom scan.");return{run:saved,matchCount,sourceResults:results};}catch(error){await repo.finishRun(run.id,{status:"failed",matchCount:0,summary:{sourceIds:profile.source_ids,filters:profile.filters},error:error instanceof Error?error.message:"Custom scan failed"}).catch(()=>undefined);throw error;}}});}
export async function processPhase9Cycle(options:{repo?:AlertsRepository;billing?:BillingRepository;email?:EmailProvider;now?:Date}={}){const repo=options.repo??new AlertsRepository(),billing=options.billing??new BillingRepository(),email=options.email??configuredEmailProvider(),now=options.now??new Date();const generated=await repo.generateNotifications(now)+await repo.generateHighMatches();const due=await repo.claimDueScanners(now);const scans=[];for(const scanner of due){try{scans.push(await runCustomScanner(scanner.user_id,scanner.id,{repo,billing,idempotencyKey:`scheduled-custom-scan:${scanner.id}:${scanner.next_run_at}`}));}catch(error){scans.push({error:error instanceof Error?error.message:"Custom scan failed"});}}const digests=[];for(const kind of ["daily","weekly"] as const)digests.push(...await processDigests(kind,repo,email,now));return{generated,scans,digests};}
export async function processDigests(kind:"daily"|"weekly",repo=new AlertsRepository(),email=configuredEmailProvider(),now=new Date()){const windowMs=kind==="daily"?86400000:7*86400000,windowStart=new Date(now.getTime()-windowMs).toISOString(),windowEnd=now.toISOString(),results=[];for(const user of await repo.digestCandidates(kind,now)){const run=await repo.claimDigest(user.id,kind,windowStart,windowEnd);if(!run)continue;const items=await repo.digestItems(user.id,windowStart,user.preferences);if(!items.length){await repo.finishDigest(run.id,"skipped",0);results.push({userId:user.id,status:"skipped"});continue;}try{const unsubscribe=`${(process.env.APP_BASE_URL??"http://localhost:5173").split(",")[0]}/dashboard/alerts`;const lines=items.map((item:any)=>`• ${item.title}: ${item.body}`);const sent=await email.send({to:user.email,subject:`Play Pack Pilot ${kind} flight briefing`,text:[`Hello ${user.display_name},`,"",...lines,"",`Manage notification preferences: ${unsubscribe}`].join("\n"),html:`<h1>${kind==="daily"?"Daily":"Weekly"} flight briefing</h1><p>Play Pack Pilot is a discovery service, not the promotion sponsor. Verify official rules.</p><ul>${items.map((item:any)=>`<li><strong>${escapeHtml(item.title)}</strong> ${escapeHtml(item.body)}</li>`).join("")}</ul><p><a href="${unsubscribe}">Manage notification preferences</a></p>`,headers:{"List-Unsubscribe":`<${unsubscribe}>`}});await repo.finishDigest(run.id,"delivered",items.length);results.push({userId:user.id,status:"delivered",messageId:sent.messageId});}catch(error){await repo.finishDigest(run.id,"failed",items.length,error instanceof Error?error.message:"Delivery failed");results.push({userId:user.id,status:"failed"});}}return results;}
async function validateScanner(userId:string,input:Record<string,unknown>,repo:AlertsRepository,billing:BillingRepository){const subscription=await billing.subscription(userId);const planKey=["active","trialing","past_due"].includes(subscription.status)?subscription.planKey:"free_flight";const policy=customScanPolicy(planKey);if(!policy.enabled)throw new AppConfigError("Custom scanning requires Ace Pilot or Squadron.");const cadenceMinutes=bounded(input.cadenceMinutes,policy.minimumCadenceMinutes,43200);if(cadenceMinutes<policy.minimumCadenceMinutes)throw new AppConfigError(`Your plan allows custom scans no more frequently than every ${policy.minimumCadenceMinutes} minutes.`);const sourceIds=Array.isArray(input.sourceIds)?[...new Set(input.sourceIds.map(String))].slice(0,25):[];if(!sourceIds.length)throw new AppConfigError("Select at least one approved source.");const approved=await repo.approvedSources(sourceIds);if(approved.length!==sourceIds.length)throw new AppConfigError("Custom scans may use only approved sources with enabled adapters and completed robots and terms reviews.");return{policy,parsed:{name:text(input.name,120,"Scanner name is required."),filters:sanitizeFilters(input.filters),sourceIds,cadenceMinutes}};}
export function sanitizeFilters(value:unknown):CustomScanFilters{const source=value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};const output:CustomScanFilters={};for(const key of ["keywords","sponsor","prizeType","country","region","category"] as const)if(typeof source[key]==="string"&&source[key].trim())output[key]=source[key].trim().slice(0,160);if(source.minimumValue!==undefined)output.minimumValue=bounded(source.minimumValue,0,100000000);if(source.maximumEffort!==undefined)output.maximumEffort=bounded(source.maximumEffort,0,100);if(typeof source.deadlineBefore==="string"&&!Number.isNaN(Date.parse(source.deadlineBefore)))output.deadlineBefore=new Date(source.deadlineBefore).toISOString();return output;}
function bounded(value:unknown,min:number,max:number){const parsed=Number(value);if(!Number.isInteger(parsed)||parsed<min||parsed>max)throw new AppConfigError(`Value must be an integer from ${min} to ${max}.`);return parsed;}
function text(value:unknown,max:number,message:string){const result=String(value??"").trim().slice(0,max);if(!result)throw new AppConfigError(message);return result;}
function escapeHtml(value:unknown){return String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]!));}
