import assert from "node:assert/strict";
import test from "node:test";
import { createCustomScanner, customScanPolicy, filterDigestItems, isDigestDue, mapPreferences, parsePreferences, processDigests, runCustomScanner, sanitizeFilters } from "../dist/alerts.mjs";

test("custom scan catalog enforces paid plan profile, cadence, and monthly limits",()=>{assert.equal(customScanPolicy("free_flight").enabled,false);assert.equal(customScanPolicy("ace_pilot").minimumCadenceMinutes,1440);assert.equal(customScanPolicy("squadron").monthlyRuns,100);});
test("custom scan filters are allowlisted and bounded",()=>{assert.deepEqual(sanitizeFilters({keywords:" travel ",sponsor:"Sponsor",minimumValue:500,maximumEffort:20,ignored:"secret"}),{keywords:"travel",sponsor:"Sponsor",minimumValue:500,maximumEffort:20});assert.throws(()=>sanitizeFilters({minimumValue:-1}),/integer/);});
test("custom scanner creation requires eligible plan and approved sources",async()=>{const billing={subscription:async()=>({planKey:"ace_pilot",status:"active"})};let saved;const repo={countScanners:async()=>0,approvedSources:async(ids)=>ids.map(id=>({id})),createScanner:async(_user,input)=>(saved=input,input)};await createCustomScanner("user-1",{name:"Travel",filters:{keywords:"trip"},sourceIds:["source-1"],cadenceMinutes:1440},repo,billing);assert.equal(saved.sourceIds[0],"source-1");await assert.rejects(()=>createCustomScanner("user-1",{name:"Bad",sourceIds:["source-1"],cadenceMinutes:1440},{...repo,approvedSources:async()=>[]},billing),/approved sources/);await assert.rejects(()=>createCustomScanner("user-1",{name:"Free",sourceIds:["source-1"],cadenceMinutes:43200},repo,{subscription:async()=>({planKey:"free_flight",status:"none"})}),/requires Ace Pilot/);});
test("custom scan consumes credits once, records results, and returns duplicate runs without re-execution",async()=>{const events=[];const profile={id:"scan-1",user_id:"user-1",name:"Travel",filters:{keywords:"trip"},source_ids:["source-1"],cadence_minutes:1440,next_run_at:"2026-07-24T00:00:00Z"};let existing=null;const repo={scanner:async()=>profile,countMonthlyRuns:async()=>0,runByCreditKey:async()=>existing,createRun:async()=>({id:"run-1"}),matchCount:async()=>4,finishRun:async(_id,input)=>({id:"run-1",...input}),};const billing={subscription:async()=>({planKey:"ace_pilot",status:"active"}),consume:async(_user,input)=>events.push(["consume",input]),ledger:async()=>({balance:90}),refund:async()=>events.push(["refund"])};const scanner={runSource:async()=>({sourceId:"source-1",status:"completed",discovered:2})};const first=await runCustomScanner("user-1","scan-1",{repo,billing,scanner,idempotencyKey:"key-1"});assert.equal(first.cost,10);assert.equal(first.value.matchCount,4);assert.equal(events.filter(x=>x[0]==="consume").length,1);existing={id:"run-1",match_count:4,result_summary:{sources:[]}};const duplicate=await runCustomScanner("user-1","scan-1",{repo,billing,scanner,idempotencyKey:"key-1"});assert.equal(duplicate.cost,0);assert.equal(events.filter(x=>x[0]==="consume").length,1);});
test("failed custom scan records failure and refunds the exact credit charge",async()=>{const events=[];const profile={id:"scan-1",user_id:"user-1",name:"Travel",filters:{},source_ids:["source-1"],cadence_minutes:1440,next_run_at:"2026-07-24T00:00:00Z"};const repo={scanner:async()=>profile,countMonthlyRuns:async()=>0,runByCreditKey:async()=>null,createRun:async()=>({id:"run-1"}),matchCount:async()=>0,finishRun:async(_id,input)=>input};const billing={subscription:async()=>({planKey:"ace_pilot",status:"active"}),consume:async()=>events.push("consume"),ledger:async()=>({balance:90}),refund:async(_user,charge,refund)=>events.push(`${charge}:${refund}`)};await assert.rejects(()=>runCustomScanner("user-1","scan-1",{repo,billing,scanner:{runSource:async()=>{throw new Error("source failed");}},idempotencyKey:"key-fail"}),/All approved sources failed/);assert.ok(events.includes("key-fail:refund:key-fail"));});
test("digest scheduling honors user timezone and weekly Monday window",()=>{const monday=new Date("2026-07-27T12:00:00Z");assert.equal(isDigestDue("America/New_York","daily",monday),true);assert.equal(isDigestDue("America/New_York","weekly",new Date("2026-07-27T13:00:00Z")),true);assert.equal(isDigestDue("America/Los_Angeles","daily",monday),false);assert.equal(isDigestDue("Not/AZone","daily",monday),false);});
test("unsubscribe preferences disable email while retaining in-app delivery",()=>{const prefs=parsePreferences({inAppEnabled:true,emailEnabled:false,dailyDigestEnabled:true});assert.equal(prefs.inAppEnabled,true);assert.equal(prefs.emailEnabled,false);});
test("accounts without notification preferences remain email opt-out",()=>{assert.equal(mapPreferences(null).emailEnabled,false);});
test("digest content honors category and reminder preferences",()=>{const prefs={...mapPreferences(null),endingSoonEnabled:false,highValueEnabled:false,recommendationsEnabled:false,entryRemindersEnabled:false};assert.deepEqual(filterDigestItems([{type:"ending_soon"},{type:"high_match"},{type:"entry_due"},{type:"rules_changed"}],prefs),[{type:"rules_changed"}]);});
test("failed email delivery is retained as a failed digest for retry operations",async()=>{const finished=[];const repo={digestCandidates:async()=>[{id:"user-1",email:"pilot@example.com",display_name:"Pilot"}],claimDigest:async()=>({id:"digest-1"}),digestItems:async()=>[{title:"Ending soon",body:"Review rules"}],finishDigest:async(...args)=>finished.push(args)};const result=await processDigests("daily",repo,{send:async()=>{throw new Error("provider unavailable");}},new Date("2026-07-27T12:00:00Z"));assert.equal(result[0].status,"failed");assert.equal(finished[0][1],"failed");});
