import assert from "node:assert/strict";
import { createHmac } from "node:crypto";
import test from "node:test";
import { assertOperationAllowed, changeSubscription, createCheckout, createPortal, grantPaidPeriod, handleWebhook, InsufficientCreditsError, setCancellation, verifyStripeSignature, withPilotCredits } from "../dist/billing.mjs";

process.env.STRIPE_SECRET_KEY="sk_test_phase8";process.env.STRIPE_WEBHOOK_SECRET="whsec_phase8";process.env.APP_BASE_URL="https://playpackpilot.test";process.env.STRIPE_PRICE_COPILOT_MONTHLY="price_copilot_month";process.env.STRIPE_PRICE_COPILOT_ANNUAL="price_copilot_year";process.env.STRIPE_PRICE_ACE_PILOT_MONTHLY="price_ace_month";process.env.STRIPE_PRICE_ACE_PILOT_ANNUAL="price_ace_year";process.env.STRIPE_PRICE_SQUADRON_MONTHLY="price_squadron_month";process.env.STRIPE_PRICE_SQUADRON_ANNUAL="price_squadron_year";

test("checkout uses authenticated user and trusted server Price and redirect configuration",async()=>{const requests=[];const repo={profile:async(id)=>({id,email:"pilot@example.com",display_name:"Pilot"}),customer:async()=>undefined,saveCustomer:async()=>{}};const fetcher=async(url,init)=>{requests.push({url,body:String(init.body)});return response(requests.length===1?{id:"cus_1"}:{id:"cs_1",url:"https://checkout.stripe.test/session"});};const result=await createCheckout("user-1",{planKey:"co_pilot",interval:"month"},repo,fetcher);assert.equal(result.checkoutUrl,"https://checkout.stripe.test/session");const body=new URLSearchParams(requests[1].body);assert.equal(body.get("line_items[0][price]"),"price_copilot_month");assert.equal(body.get("client_reference_id"),"user-1");assert.equal(body.get("success_url"),"https://playpackpilot.test/dashboard/billing?checkout=success");assert.equal(body.has("origin"),false);});
test("customer portal, upgrade, downgrade, cancel, and resume call Stripe server-side",async()=>{const calls=[];const subscription={userId:"user-1",providerSubscriptionId:"sub_1",planKey:"co_pilot",status:"active"};const repo={customer:async()=>"cus_1",subscription:async()=>subscription};const fetcher=async(url,init={})=>{calls.push({url,method:init.method,body:String(init.body??"")});if(init.method==="GET")return response({items:{data:[{id:"si_1"}]}});return response(url.includes("billing_portal")?{url:"https://billing.stripe.test/portal"}:{});};assert.match((await createPortal("user-1",repo,fetcher)).portalUrl,/billing\.stripe/);await changeSubscription("user-1",{planKey:"squadron",interval:"year"},repo,fetcher);await changeSubscription("user-1",{planKey:"co_pilot",interval:"month"},repo,fetcher);await setCancellation("user-1",true,repo,fetcher);await setCancellation("user-1",false,repo,fetcher);assert.ok(calls.some((call)=>call.body.includes("price_squadron_year")));assert.ok(calls.some((call)=>call.body.includes("price_copilot_month")));assert.ok(calls.some((call)=>call.body.includes("cancel_at_period_end=true")));assert.ok(calls.some((call)=>call.body.includes("cancel_at_period_end=false")));});
test("signature verification rejects missing, stale, and invalid signatures",()=>{const body=Buffer.from("{}");assert.throws(()=>verifyStripeSignature(body,undefined,"whsec",1000),/missing/);assert.throws(()=>verifyStripeSignature(body,sign(body,"whsec",1),"whsec",1000),/tolerance/);assert.throws(()=>verifyStripeSignature(body,sign(body,"wrong",1000),"whsec",1000),/failed/);verifyStripeSignature(body,sign(body,"whsec",1000),"whsec",1000);});
test("duplicate webhook delivery is ignored before side effects",async()=>{const event=eventBody("evt_duplicate","invoice.paid",{});const repo={claimEvent:async()=>false};assert.deepEqual(await handleWebhook(event,sign(event,process.env.STRIPE_WEBHOOK_SECRET),repo),{duplicate:true,eventId:"evt_duplicate"});});
test("subscription activation synchronizes trusted plan, status, and entitlements",async()=>{const state=fakeWebhookRepo();const object={id:"sub_1",customer:"cus_1",status:"active",current_period_start:1780000000,current_period_end:1782592000,metadata:{user_id:"user-1"},items:{data:[{price:{id:"price_ace_month"}}]}};const body=eventBody("evt_sub","customer.subscription.updated",object);const result=await handleWebhook(body,sign(body,process.env.STRIPE_WEBHOOK_SECRET),state);assert.equal(result.subscription.planKey,"ace_pilot");assert.equal(state.saved.status,"active");assert.equal(state.entitlement.planKey,"ace_pilot");assert.equal(state.finished.status,"processed");});
test("paid invoice grants included credits once by invoice id and failed invoice enters past due grace",async()=>{const paid=fakeWebhookRepo();paid.current.planKey="ace_pilot";const invoice={id:"in_1",customer:"cus_1",subscription:"sub_1",metadata:{user_id:"user-1"},lines:{data:[{period:{start:1780000000,end:1782592000}}]}};let body=eventBody("evt_paid","invoice.paid",invoice);await handleWebhook(body,sign(body,process.env.STRIPE_WEBHOOK_SECRET),paid);assert.equal(paid.grant.amount,750);assert.equal(paid.grant.idempotencyKey,"stripe-invoice:in_1");const failed=fakeWebhookRepo();failed.current.planKey="co_pilot";body=eventBody("evt_failed","invoice.payment_failed",invoice);await handleWebhook(body,sign(body,process.env.STRIPE_WEBHOOK_SECRET),failed);assert.equal(failed.saved.status,"past_due");assert.ok(failed.entitlement.activeUntil);});
test("monthly grants use stable duplicate-prevention keys",async()=>{const calls=[];const repo={grant:async(_user,input)=>{calls.push(input);return{applied:calls.length===1};}};await grantPaidPeriod("user-1","co_pilot","in_same",null,repo);await grantPaidPeriod("user-1","co_pilot","in_same",null,repo);assert.equal(calls[0].idempotencyKey,calls[1].idempotencyKey);assert.equal(calls[0].amount,200);});
test("central credit service consumes, rejects plan-ineligible work, and refunds failed actions",async()=>{const events=[];const repo={subscription:async()=>({planKey:"ace_pilot",status:"active"}),consume:async(_user,input)=>events.push(["consume",input]),ledger:async()=>({balance:17}),refund:async(_user,charge,refund)=>events.push(["refund",{charge,refund}])};const success=await withPilotCredits({userId:"user-1",operation:"rules_summary",sourceReference:"sweep-1",idempotencyKey:"charge-1",repository:repo,execute:async()=>"done"});assert.equal(success.cost,2);assert.equal(success.balance,17);await assert.rejects(()=>withPilotCredits({userId:"user-1",operation:"official_rules_extraction",sourceReference:"sweep-2",idempotencyKey:"charge-2",repository:repo,execute:async()=>{throw new Error("provider failed");}}),/provider failed/);assert.equal(events.filter(([type])=>type==="refund").length,1);assert.throws(()=>assertOperationAllowed("free_flight","custom_scan"),/Upgrade/);});
test("central credit service stops work when the authoritative ledger is insufficient",async()=>{let executed=false;const repo={subscription:async()=>({planKey:"ace_pilot",status:"active"}),consume:async()=>{throw new InsufficientCreditsError();},ledger:async()=>({balance:3}),refund:async()=>{throw new Error("refund must not run when no charge was created");}};await assert.rejects(()=>withPilotCredits({userId:"user-1",operation:"official_rules_extraction",sourceReference:"sweep-3",idempotencyKey:"charge-3",repository:repo,execute:async()=>{executed=true;}}),error=>error instanceof InsufficientCreditsError);assert.equal(executed,false);});

function fakeWebhookRepo(){const state={current:{userId:"user-1",providerSubscriptionId:"sub_1",providerPriceId:"price_copilot_month",planKey:"co_pilot",status:"active",currentPeriodStart:null,currentPeriodEnd:null,cancelAtPeriodEnd:false,trialEnd:null,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()},claimEvent:async()=>true,subscriptionOwner:async()=>"user-1",subscription:async()=>state.current,saveSubscription:async(input)=>(state.saved=input,state.current=input,input),replaceEntitlements:async(_user,planKey,_source,activeUntil)=>(state.entitlement={planKey,activeUntil}),finishEvent:async(_id,input)=>(state.finished=input),grant:async(_user,input)=>(state.grant=input,{applied:true})};return state;}
function response(payload){return{ok:true,status:200,json:async()=>payload};}
function eventBody(id,type,object){return Buffer.from(JSON.stringify({id,type,livemode:false,data:{object}}));}
function sign(body,secret,timestamp=Math.floor(Date.now()/1000)){return`t=${timestamp},v1=${createHmac("sha256",secret).update(`${timestamp}.${body.toString("utf8")}`).digest("hex")}`;}
