import { randomUUID } from "node:crypto";
import { getPlan, operationCost } from "./catalog";
import { BillingRepository } from "./repository";
import type { CreditOperation, PlanKey } from "./types";

export async function ensureFreeMonthlyGrant(userId:string,repo=new BillingRepository(),now=new Date()) { const month=now.toISOString().slice(0,7); const plan=getPlan("free_flight"); return repo.grant(userId,{amount:plan.monthlyCredits,reasonCode:"free_monthly_included",sourceReference:month,idempotencyKey:`free-monthly:${userId}:${month}`,expiresAt:endOfFollowingMonth(now).toISOString(),metadata:{planKey:plan.key,policy:"free_monthly_access"}}); }
export async function grantPaidPeriod(userId:string,planKey:PlanKey,invoiceId:string,periodEnd:string|null,repo=new BillingRepository()){const plan=getPlan(planKey);return repo.grant(userId,{amount:plan.monthlyCredits,reasonCode:"subscription_period_included",sourceReference:invoiceId,idempotencyKey:`stripe-invoice:${invoiceId}`,expiresAt:periodEnd,metadata:{planKey}});}

export async function withPilotCredits<T>(input:{userId:string;operation:CreditOperation;sourceReference:string;idempotencyKey?:string;metadata?:Record<string,unknown>;execute:()=>Promise<T>;repository?:BillingRepository}) { const repository=input.repository??new BillingRepository(); const chargeKey=input.idempotencyKey??`operation:${input.userId}:${input.operation}:${randomUUID()}`; const cost=operationCost(input.operation); await repository.consume(input.userId,{amount:cost,reasonCode:input.operation,sourceReference:input.sourceReference,idempotencyKey:chargeKey,metadata:input.metadata}); try { const value=await input.execute(); return {value,cost,balance:(await repository.ledger(input.userId)).balance}; } catch(error) { await repository.refund(input.userId,chargeKey,`refund:${chargeKey}`,{error:error instanceof Error?error.name:"unknown"}); throw error; } }
function endOfFollowingMonth(now:Date){return new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+2,1));}
