import { getSupabaseServiceClient } from "@/lib/auth/session";
import { getPlan } from "./catalog";
import type { PlanKey, SubscriptionRecord } from "./types";

export class BillingRepository {
  private readonly client: any;
  constructor(client: any = getSupabaseServiceClient()) { this.client = client; }
  async profile(userId: string) { const result=await this.client.from("profiles").select("id,email,display_name").eq("id",userId).single(); check(result,"Billing profile was not found."); return result.data; }
  async customer(userId: string) { const result=await this.client.from("billing_customers").select("provider_customer_id").eq("user_id",userId).eq("provider","stripe").maybeSingle(); check(result,"Unable to load the billing customer."); return result.data?.provider_customer_id as string|undefined; }
  async customerOwner(providerCustomerId: string) { const result=await this.client.from("billing_customers").select("user_id").eq("provider","stripe").eq("provider_customer_id",providerCustomerId).maybeSingle(); check(result,"Unable to resolve the billing customer."); return result.data?.user_id as string|undefined; }
  async saveCustomer(userId:string,customerId:string) { const result=await this.client.from("billing_customers").upsert({user_id:userId,provider:"stripe",provider_customer_id:customerId,updated_at:new Date().toISOString()},{onConflict:"user_id,provider"}); check(result,"Unable to save the billing customer."); }
  async subscription(userId:string):Promise<SubscriptionRecord> { const result=await this.client.from("subscriptions").select("*").eq("user_id",userId).maybeSingle(); check(result,"Unable to load the subscription."); return result.data?mapSubscription(result.data):freeSubscription(userId); }
  async subscriptionOwner(input:{subscriptionId?:string|null;customerId?:string|null}) { if(input.subscriptionId){const result=await this.client.from("subscriptions").select("user_id").eq("provider_subscription_id",input.subscriptionId).maybeSingle(); check(result,"Unable to resolve the subscription."); if(result.data?.user_id)return String(result.data.user_id);} return input.customerId?this.customerOwner(input.customerId):undefined; }
  async saveSubscription(input:SubscriptionRecord) { const result=await this.client.from("subscriptions").upsert({user_id:input.userId,provider_subscription_id:input.providerSubscriptionId,provider_price_id:input.providerPriceId,plan_key:input.planKey,status:input.status,current_period_start:input.currentPeriodStart,current_period_end:input.currentPeriodEnd,cancel_at_period_end:input.cancelAtPeriodEnd,trial_end:input.trialEnd,updated_at:new Date().toISOString()},{onConflict:"user_id"}).select("*").single(); check(result,"Unable to synchronize the subscription."); return mapSubscription(result.data); }
  async replaceEntitlements(userId:string,planKey:PlanKey,source:string,activeUntil:string|null) { const removed=await this.client.from("entitlements").delete().eq("user_id",userId).eq("source",source); check(removed,"Unable to refresh entitlements."); const features=getPlan(planKey).features; const rows=Object.entries(features).filter(([,value])=>value!==false&&value!==0).map(([feature,value])=>({user_id:userId,feature_key:feature,limit_value:typeof value==="number"?value:null,active_until:activeUntil,source})); if(rows.length){const inserted=await this.client.from("entitlements").insert(rows); check(inserted,"Unable to write entitlements.");} }
  async entitlements(userId:string){const result=await this.client.from("entitlements").select("feature_key,limit_value,active_from,active_until,source").eq("user_id",userId).or(`active_until.is.null,active_until.gt.${new Date().toISOString()}`);check(result,"Unable to load entitlements.");return result.data??[];}
  async claimEvent(id:string,type:string,metadata:Record<string,unknown>){const result=await this.client.rpc("claim_billing_event",{p_provider_event_id:id,p_event_type:type,p_metadata:metadata});check(result,"Unable to claim the billing event.");return result.data===true;}
  async finishEvent(id:string,input:{status:"processed"|"failed"|"ignored";userId?:string;error?:string;metadata?:Record<string,unknown>}){const result=await this.client.from("billing_events").update({status:input.status,user_id:input.userId,processed_at:new Date().toISOString(),error_message:input.error??null,...(input.metadata?{metadata:input.metadata}:{})}).eq("provider_event_id",id);check(result,"Unable to finalize the billing event.");}
  async history(userId:string){const result=await this.client.from("billing_events").select("provider_event_id,event_type,status,received_at,processed_at,error_message,metadata").eq("user_id",userId).order("received_at",{ascending:false}).limit(50);check(result,"Unable to load billing history.");return result.data??[];}
  async ledger(userId:string){const [balance,entries]=await Promise.all([this.client.rpc("pilot_credit_balance",{p_user_id:userId}),this.client.from("credit_ledger").select("id,amount,entry_type,reason_code,source_reference,expires_at,metadata,created_at").eq("user_id",userId).order("created_at",{ascending:false}).limit(100)]);check(balance,"Unable to calculate Pilot Credits.");check(entries,"Unable to load Pilot Credit history.");return {balance:Number(balance.data??0),entries:entries.data??[]};}
  async grant(userId:string,input:{amount:number;reasonCode:string;sourceReference:string;idempotencyKey:string;expiresAt?:string|null;metadata?:Record<string,unknown>}){const result=await this.client.rpc("grant_pilot_credits",{p_user_id:userId,p_amount:input.amount,p_reason_code:input.reasonCode,p_source_reference:input.sourceReference,p_idempotency_key:input.idempotencyKey,p_expires_at:input.expiresAt??null,p_metadata:input.metadata??{}});check(result,"Unable to grant Pilot Credits.");return first(result.data);}
  async consume(userId:string,input:{amount:number;reasonCode:string;sourceReference:string;idempotencyKey:string;metadata?:Record<string,unknown>}){const result=await this.client.rpc("consume_pilot_credits",{p_user_id:userId,p_amount:input.amount,p_reason_code:input.reasonCode,p_source_reference:input.sourceReference,p_idempotency_key:input.idempotencyKey,p_metadata:input.metadata??{}});if(result.error&&String(result.error.message).includes("INSUFFICIENT_PILOT_CREDITS"))throw new InsufficientCreditsError();check(result,"Unable to consume Pilot Credits.");return first(result.data);}
  async refund(userId:string,chargeKey:string,refundKey:string,metadata?:Record<string,unknown>){const result=await this.client.rpc("refund_pilot_credits",{p_user_id:userId,p_charge_idempotency_key:chargeKey,p_refund_idempotency_key:refundKey,p_metadata:metadata??{}});check(result,"Unable to refund Pilot Credits.");return first(result.data);}
}
export class InsufficientCreditsError extends Error { constructor(){super("Insufficient Pilot Credits. Upgrade your plan or wait for the next included-credit grant.");this.name="InsufficientCreditsError";} }
function mapSubscription(row:any):SubscriptionRecord{return{userId:row.user_id,providerSubscriptionId:row.provider_subscription_id,providerPriceId:row.provider_price_id,planKey:row.plan_key,status:row.status,currentPeriodStart:row.current_period_start,currentPeriodEnd:row.current_period_end,cancelAtPeriodEnd:Boolean(row.cancel_at_period_end),trialEnd:row.trial_end,createdAt:row.created_at,updatedAt:row.updated_at};}
function freeSubscription(userId:string):SubscriptionRecord{const now=new Date().toISOString();return{userId,providerSubscriptionId:null,providerPriceId:null,planKey:"free_flight",status:"none",currentPeriodStart:null,currentPeriodEnd:null,cancelAtPeriodEnd:false,trialEnd:null,createdAt:now,updatedAt:now};}
function check(result:any,message:string){if(result?.error)throw new Error(`${message} ${result.error.message??""}`.trim());}
function first(data:any){return Array.isArray(data)?data[0]:data;}
