import { creditCosts, getPlan, publicCatalog } from "./catalog";
import { ensureFreeMonthlyGrant } from "./credits";
import { BillingRepository, resolveEffectivePlan } from "./repository";

export async function billingSummary(userId:string,repo=new BillingRepository()){const effective=await resolveEffectivePlan(repo,userId),subscription=effective.subscription;if(subscription.planKey==="free_flight"&&(subscription.status==="none"||subscription.status==="canceled"))await ensureFreeMonthlyGrant(userId,repo);let entitlements=await repo.entitlements(userId);if(!entitlements.length){await repo.replaceEntitlements(userId,"free_flight","free_policy",null);entitlements=await repo.entitlements(userId);}const [credits,history]=await Promise.all([repo.ledger(userId),repo.history(userId)]),override=effective.accessPlanOverride;
  // An active administrative override governs the effective app plan/features
  // while the Stripe subscription record above stays unchanged.
  const effectivePlanKey=override?override.planKey:subscription.planKey;const effectiveEntitlements=entitlements.filter((item:any)=>override?item.source==="admin_override":item.source!=="admin_override");const plan=getPlan(effectivePlanKey);return{catalog:publicCatalog(),creditCosts:creditCosts(),subscription,effectivePlanKey,accessPlanOverride:override,plan:{...plan,prices:undefined},entitlements:effectiveEntitlements,credits,billingHistory:history,stripe:{testMode:true,configured:Boolean(process.env.STRIPE_SECRET_KEY?.startsWith("sk_test_")),portalAvailable:Boolean(await repo.customer(userId))},paymentFailed:subscription.status==="past_due"||subscription.status==="unpaid",gracePeriodDays:bounded(process.env.BILLING_GRACE_PERIOD_DAYS,3)};}
function bounded(value:unknown,fallback:number){const n=Number(value);return Number.isInteger(n)&&n>=0&&n<=30?n:fallback;}
