import { createHmac, timingSafeEqual } from "node:crypto";
import { AppConfigError } from "@/lib/env";
import { getPrice, planForPrice } from "./catalog";
import { grantPaidPeriod } from "./credits";
import { BillingRepository } from "./repository";
import type { BillingInterval, PlanKey, StripeEvent, SubscriptionRecord } from "./types";

type Fetcher = typeof fetch;
export async function createCheckout(userId:string,input:{planKey:PlanKey;interval:BillingInterval},repo=new BillingRepository(),fetcher:Fetcher=fetch){const {plan,priceId}=getPrice(input.planKey,input.interval);const profile=await repo.profile(userId);let customerId=await repo.customer(userId);if(!customerId){const customer=await stripePost("/customers",{"email":String(profile.email),"name":String(profile.display_name),"metadata[user_id]":userId},fetcher);customerId=required(string(customer.id),"Stripe customer creation returned no ID.");await repo.saveCustomer(userId,customerId);}const resolvedCustomerId=required(customerId,"Stripe customer is unavailable.");const base=appBaseUrl();const session=await stripePost("/checkout/sessions",{mode:"subscription",customer:resolvedCustomerId,"line_items[0][price]":priceId,"line_items[0][quantity]":"1",client_reference_id:userId,"metadata[user_id]":userId,"metadata[plan_key]":plan.key,"subscription_data[metadata][user_id]":userId,success_url:`${base}/dashboard/billing?checkout=success`,cancel_url:`${base}/pricing?checkout=cancelled`,allow_promotion_codes:"true"},fetcher);return{checkoutUrl:required(string(session.url),"Stripe Checkout returned no URL."),sessionId:string(session.id),planKey:plan.key,interval:input.interval};}
export async function createPortal(userId:string,repo=new BillingRepository(),fetcher:Fetcher=fetch){const customer=await repo.customer(userId);if(!customer)throw new AppConfigError("No Stripe customer exists for this account.");const session=await stripePost("/billing_portal/sessions",{customer,return_url:`${appBaseUrl()}/dashboard/billing`},fetcher);return{portalUrl:required(session.url,"Stripe Portal returned no URL.")};}
export async function changeSubscription(userId:string,input:{planKey:PlanKey;interval:BillingInterval},repo=new BillingRepository(),fetcher:Fetcher=fetch){const current=await repo.subscription(userId);if(!current.providerSubscriptionId)throw new AppConfigError("No paid subscription is available to change.");const {plan,priceId}=getPrice(input.planKey,input.interval);const remote=await stripeGet(`/subscriptions/${encodeURIComponent(current.providerSubscriptionId)}`,fetcher);const itemId=required(record(remote.items).data?.[0]?.id,"Stripe subscription item was not found.");await stripePost(`/subscriptions/${encodeURIComponent(current.providerSubscriptionId)}`,{[`items[0][id]`]:itemId,[`items[0][price]`]:priceId,proration_behavior:"create_prorations","metadata[user_id]":userId},fetcher);return{pendingWebhookSync:true,planKey:plan.key,interval:input.interval};}
export async function setCancellation(userId:string,cancelAtPeriodEnd:boolean,repo=new BillingRepository(),fetcher:Fetcher=fetch){const current=await repo.subscription(userId);if(!current.providerSubscriptionId)throw new AppConfigError("No paid subscription is available to update.");await stripePost(`/subscriptions/${encodeURIComponent(current.providerSubscriptionId)}`,{cancel_at_period_end:String(cancelAtPeriodEnd)},fetcher);return{pendingWebhookSync:true,cancelAtPeriodEnd};}

export async function handleWebhook(rawBody:Buffer,signature:string|undefined,repo=new BillingRepository()){const event=parseWebhook(rawBody,signature);const claimed=await repo.claimEvent(event.id,event.type,{livemode:Boolean((event as any).livemode)});if(!claimed)return{duplicate:true,eventId:event.id};let userId:string|undefined;try{const object=event.data.object;if(event.type==="checkout.session.completed"){const checkoutUserId=string(record(object.metadata).user_id)??string(object.client_reference_id);if(!checkoutUserId)throw new AppConfigError("Checkout event is missing user metadata.");userId=checkoutUserId;const customer=required(string(object.customer),"Checkout event is missing its customer.");await repo.saveCustomer(userId,customer);await repo.finishEvent(event.id,{status:"processed",userId,metadata:{checkoutRecorded:true}});return{duplicate:false,eventId:event.id,type:event.type};}
if(event.type.startsWith("customer.subscription.")){userId=await resolveOwner(object,repo);if(!userId)throw new AppConfigError("Subscription event cannot be associated with a user.");const saved=await syncSubscription(userId,object,event.type==="customer.subscription.deleted",repo);await repo.finishEvent(event.id,{status:"processed",userId,metadata:{planKey:saved.planKey,status:saved.status}});return{duplicate:false,eventId:event.id,type:event.type,subscription:saved};}
if(event.type==="invoice.paid"||event.type==="invoice.payment_failed"){userId=await resolveOwner(object,repo);if(!userId)throw new AppConfigError("Invoice event cannot be associated with a user.");const current=await repo.subscription(userId);if(event.type==="invoice.paid"){const period=invoicePeriod(object);await grantPaidPeriod(userId,current.planKey,required(string(object.id),"Invoice is missing its ID."),period.end,repo);const active={...current,status:"active",currentPeriodStart:period.start??current.currentPeriodStart,currentPeriodEnd:period.end??current.currentPeriodEnd,updatedAt:new Date().toISOString()};await repo.saveSubscription(active);await repo.replaceEntitlements(userId,active.planKey,"stripe_subscription",active.currentPeriodEnd);}else{const graceDays=boundedInt(process.env.BILLING_GRACE_PERIOD_DAYS,3,0,30);const graceUntil=new Date(Date.now()+graceDays*86400000).toISOString();await repo.saveSubscription({...current,status:"past_due",updatedAt:new Date().toISOString()});await repo.replaceEntitlements(userId,current.planKey,"stripe_subscription",graceUntil);}await repo.finishEvent(event.id,{status:"processed",userId,metadata:{invoiceId:string(object.id),payment:event.type==="invoice.paid"?"paid":"failed"}});return{duplicate:false,eventId:event.id,type:event.type};}
await repo.finishEvent(event.id,{status:"ignored"});return{duplicate:false,eventId:event.id,ignored:true,type:event.type};}catch(error){await repo.finishEvent(event.id,{status:"failed",userId,error:error instanceof Error?error.message:"Webhook processing failed."});throw error;}}

export function verifyStripeSignature(rawBody:Buffer,header:string|undefined,secret=webhookSecret(),nowSeconds=Math.floor(Date.now()/1000)){if(!header)throw new AppConfigError("Stripe webhook signature is missing.");const fields=header.split(",").map((part)=>part.split("=")).filter((part):part is[string,string]=>part.length===2);const timestamp=fields.find(([key])=>key==="t")?.[1];const signatures=fields.filter(([key])=>key==="v1").map(([,value])=>value);if(!timestamp||!signatures.length)throw new AppConfigError("Stripe webhook signature is malformed.");const parsed=Number(timestamp);if(!Number.isFinite(parsed)||Math.abs(nowSeconds-parsed)>300)throw new AppConfigError("Stripe webhook signature timestamp is outside the allowed tolerance.");const expected=createHmac("sha256",secret).update(`${timestamp}.${rawBody.toString("utf8")}`).digest("hex");if(!signatures.some((value)=>safeHexEqual(value,expected)))throw new AppConfigError("Stripe webhook signature verification failed.");}
export function parseWebhook(rawBody:Buffer,signature:string|undefined):StripeEvent{verifyStripeSignature(rawBody,signature);let parsed:unknown;try{parsed=JSON.parse(rawBody.toString("utf8"));}catch{throw new AppConfigError("Stripe webhook payload is malformed.");}const event=record(parsed);if(!string(event.id)||!string(event.type)||!record(event.data).object)throw new AppConfigError("Stripe webhook payload is malformed.");if(event.livemode===true)throw new AppConfigError("Live-mode Stripe events are disabled. Phase 8 starts in test mode.");return event as unknown as StripeEvent;}
async function syncSubscription(userId:string,object:Record<string,unknown>,deleted:boolean,repo:BillingRepository){const item=record(record(object.items).data?.[0]);const priceId=required(string(record(item.price).id),"Subscription event is missing a Price ID.");const {plan}=planForPrice(priceId);const status=deleted?"canceled":normalizeStatus(object.status);const saved=await repo.saveSubscription({userId,providerSubscriptionId:string(object.id),providerPriceId:priceId,planKey:deleted?"free_flight":plan.key,status,currentPeriodStart:unix(object.current_period_start),currentPeriodEnd:unix(object.current_period_end),cancelAtPeriodEnd:Boolean(object.cancel_at_period_end),trialEnd:unix(object.trial_end),createdAt:unix(object.created)??new Date().toISOString(),updatedAt:new Date().toISOString()});const active=status==="active"||status==="trialing"||status==="past_due";await repo.replaceEntitlements(userId,active?saved.planKey:"free_flight","stripe_subscription",active?saved.currentPeriodEnd:null);return saved;}
async function resolveOwner(object:Record<string,unknown>,repo:BillingRepository){return string(record(object.metadata).user_id)??repo.subscriptionOwner({subscriptionId:string(object.subscription)??string(object.id),customerId:string(object.customer)});}
async function stripePost(path:string,fields:Record<string,string>,fetcher:Fetcher){const body=new URLSearchParams();for(const [key,value] of Object.entries(fields))body.set(key,value);return stripeRequest(path,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body},fetcher);}
async function stripeGet(path:string,fetcher:Fetcher){return stripeRequest(path,{method:"GET"},fetcher);}
async function stripeRequest(path:string,init:RequestInit,fetcher:Fetcher){const response=await fetcher(`https://api.stripe.com/v1${path}`,{...init,headers:{Authorization:`Bearer ${stripeSecret()}`,...init.headers}});const payload=record(await response.json().catch(()=>({})));if(!response.ok)throw new AppConfigError(string(record(payload.error).message)??`Stripe request failed with HTTP ${response.status}.`);return payload;}
function stripeSecret(){const key=process.env.STRIPE_SECRET_KEY?.trim();if(!key)throw new AppConfigError("Stripe test mode is not configured.");if(!key.startsWith("sk_test_"))throw new AppConfigError("Only Stripe test-mode secret keys are allowed until live billing is explicitly enabled.");return key;}
function webhookSecret(){const secret=process.env.STRIPE_WEBHOOK_SECRET?.trim();if(!secret)throw new AppConfigError("Stripe webhook secret is not configured.");return secret;}
function appBaseUrl(){const first=(process.env.APP_BASE_URL??"http://localhost:5173").split(",")[0]!.trim();const url=new URL(first);if(!["http:","https:"].includes(url.protocol))throw new AppConfigError("APP_BASE_URL must be HTTP or HTTPS.");return url.origin;}
function invoicePeriod(object:Record<string,unknown>){const period=record(record(object.lines).data?.[0]?.period);return{start:unix(period.start),end:unix(period.end)};}
function unix(value:unknown){const number=Number(value);return Number.isFinite(number)&&number>0?new Date(number*1000).toISOString():null;}
function normalizeStatus(value:unknown){const allowed=new Set(["incomplete","trialing","active","past_due","unpaid","paused","canceled"]);const status=string(value)??"none";return allowed.has(status)?status:"none";}
function safeHexEqual(received:string,expected:string){if(!/^[a-f0-9]+$/i.test(received))return false;const a=Buffer.from(received,"hex"),b=Buffer.from(expected,"hex");return a.length===b.length&&timingSafeEqual(a,b);}
function boundedInt(value:unknown,fallback:number,min:number,max:number){const n=Number(value);return Number.isInteger(n)&&n>=min&&n<=max?n:fallback;}
function record(value:any):any{return value&&typeof value==="object"&&!Array.isArray(value)?value:{};}
function string(value:unknown){return typeof value==="string"&&value.trim()?value:null;}
function required<T>(value:T|null|undefined,message:string):T{if(value===null||value===undefined||value==="")throw new AppConfigError(message);return value;}
