import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const migration = await readFile(new URL("../migrations/0004_discovery_radar.sql", import.meta.url), "utf8");
test("radar search uses indexed full text and related-field search", () => { assert.match(migration, /search_document.*GENERATED ALWAYS/s); assert.match(migration, /sweepstakes_search_document_idx.*gin/s); for (const term of ["sweepstakes_prizes", "sweepstakes_categories", "sweepstakes_eligibility", "sweepstakes_entry_methods"]) assert.match(migration, new RegExp(term)); });
test("radar function excludes expired records and supports every required filter", () => { assert.match(migration, /s\.end_at IS NULL OR s\.end_at > now\(\)/); for (const parameter of ["p_category", "p_min_prize", "p_deadline_before", "p_start_after", "p_frequency", "p_max_effort", "p_country", "p_region", "p_user_age", "p_sponsor", "p_purchase_required", "p_social_required", "p_min_legitimacy", "p_min_source_confidence", "p_saved", "p_entered"]) assert.match(migration, new RegExp(parameter)); });
test("radar sorting and pagination are stable and bounded", () => { for (const sort of ["ending_soon", "highest_prize", "lowest_effort", "newest", "recently_verified", "popular", "recommended"]) assert.match(migration, new RegExp(sort)); assert.match(migration, /LIMIT greatest\(1, least\(p_limit, 100\)\)/); assert.match(migration, /OFFSET greatest\(0, p_offset\)/); });
test("personal radar state is user-owned under RLS", () => { assert.match(migration, /ENABLE ROW LEVEL SECURITY/g); assert.match(migration, /user_id = auth\.uid\(\)/); assert.match(migration, /user_saved_sweepstakes_pk/); assert.match(migration, /user_sweepstakes_status_pk/); });
test("radar RPC uses invoker security and personalized recommendation preferences", () => { assert.match(migration, /SECURITY INVOKER/); assert.doesNotMatch(migration, /SECURITY DEFINER/); assert.match(migration, /preferred_categories \? category\.slug/); assert.match(migration, /minimum_prize_value/); assert.match(migration, /maximum_entry_effort/); });
test("radar migration is additive", () => assert.doesNotMatch(migration, /\b(?:DROP|TRUNCATE|DELETE FROM)\b/i));
