import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, Database, Flag, HeartPulse, ListChecks, Play, ShieldAlert, Users } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/app-shell";
import { EmptyState, ErrorNotice, LoadingState, SectionHeader } from "@/components/dashboard-kit";
import { Badge, MetricCard, PageHeader, Panel, SubmitButton, TextInput } from "@/components/ui";
import { apiGet, apiSend } from "@/lib/api";
import { formatDate, titleCase } from "@/lib/format";
import type { AdminOperations } from "@/lib/types";

type Action={path:string;method?:"POST"|"PUT";body:Record<string,unknown>};
export default function AdminPage(){
  const qc=useQueryClient(),[selected,setSelected]=useState("");
  const query=useQuery({queryKey:["admin-operations"],queryFn:()=>apiGet<AdminOperations>("/admin/operations"),retry:false});
  const detail=useQuery({queryKey:["admin-listing",selected],queryFn:()=>apiGet<Record<string,any>>(`/admin/listings/${selected}`),enabled:Boolean(selected)});
  const action=useMutation({mutationFn:(input:Action)=>apiSend(input.path,input.method??"POST",input.body),onSuccess:async()=>{await qc.invalidateQueries();toast.success("Administrative action recorded");},onError:(error)=>toast.error(error.message)});
  if(query.isLoading)return <AppShell><PageHeader title="Platform Operations" kicker="Protected administration"/><LoadingState title="Loading operational controls"/></AppShell>;
  if(query.isError||!query.data)return <AppShell><PageHeader title="Platform Operations" kicker="Protected administration"/><ErrorNotice title="Administration unavailable" body={(query.error as Error)?.message||"Owner or administrator access is required."}/></AppShell>;
  const data=query.data,m=data.metrics;
  return <AppShell>
    <PageHeader title="Platform Operations" kicker={`${data.admin.role} access · ${data.admin.label}`} description="Maintain approved sources, listing quality, billing integrity, queues, providers, and immutable operational evidence."/>
    <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="Active users" value={m.activeUsers}/><MetricCard label="Paid subscribers" value={m.paidSubscribers}/><MetricCard label="MRR" value={`$${(m.mrrCents/100).toFixed(2)}`}/><MetricCard label="AI usage" value={`${m.aiRuns} runs`} sublabel={`${m.aiTokens.toLocaleString()} tokens · $${m.aiCostUsd.toFixed(2)}`}/><MetricCard label="Credits consumed" value={m.pilotCreditsConsumed}/><MetricCard label="Active sources" value={m.activeSources}/><MetricCard label="Failed scans" value={m.failedScans}/><MetricCard label="Listings discovered" value={m.listingsDiscovered}/><MetricCard label="Pending review" value={m.pendingReview}/><MetricCard label="Duplicate candidates" value={m.duplicateCandidates}/><MetricCard label="High risk" value={m.highRiskListings}/><MetricCard label="Webhook failures" value={m.webhookFailures}/><MetricCard label="Queue failures" value={m.queueFailures}/><MetricCard label="Application errors" value={m.recentApplicationErrors}/></div>
    <Panel className="mb-5"><SectionHeader title="Provider and queue health" eyebrow="Operational status"/><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{Object.entries(data.health).map(([name,item])=><div key={name} className="rounded-xl border border-line p-4"><p className="flex items-center justify-between gap-2 font-semibold">{titleCase(name)}<Badge tone={item.status==="healthy"?"ok":item.status==="degraded"?"danger":"warn"}>{item.status}</Badge></p><p className="mt-2 text-xs text-muted">{item.configured?"Configured":"Disabled by configuration"} · {item.failures} recent failures</p></div>)}</div></Panel>
    <div className="grid gap-5 xl:grid-cols-2">
      <Panel><SectionHeader title="Source administration" eyebrow="Policy-approved adapters"/><SourceCreate pending={action.isPending} run={action.mutate}/><div className="mt-5 grid gap-3">{data.sources.map(source=><SourceRow key={source.id} source={source} failureRate={data.sourceFailureRates.find(rate=>rate.sourceId===source.id)} run={action.mutate} pending={action.isPending}/>)}</div>{!data.sources.length?<EmptyState title="No registered sources" body="Create a source with policy reviews pending, then approve robots and terms before enabling scans."/>:null}</Panel>
      <Panel><SectionHeader title="Listing review" eyebrow="Evidence-backed decisions"/><div className="mt-4 grid gap-2">{data.listings.filter(x=>x.status==="unverifiable"||x.listing_quality_flags?.some((f:any)=>["open","reviewing"].includes(f.status))).slice(0,30).map(item=><button key={item.id} onClick={()=>setSelected(item.id)} className="rounded-lg border border-line p-3 text-left hover:border-accent"><span className="font-semibold">{item.title}</span><span className="mt-1 block text-xs text-muted">{item.sponsor_name} · confidence {item.source_confidence_score} · {item.status}</span></button>)}</div>{selected?<ListingReview listing={detail.data} id={selected} loading={detail.isLoading} run={action.mutate} pending={action.isPending}/>:<EmptyState title="Select a review candidate" body="Inspect AI evidence, rules versions, change history, correct allowlisted fields, or record a decision."/>}</Panel>
      <Panel><SectionHeader title="Users and billing" eyebrow="Append-only credit controls"/><div className="mt-4 grid gap-3">{data.users.map(user=><UserRow key={user.id} user={user} ledger={data.creditLedger.filter(entry=>entry.user_id===user.id)} owner={data.admin.role==="owner"} run={action.mutate} pending={action.isPending}/>)}</div></Panel>
      <Panel><SectionHeader title="Queue and failure review" eyebrow="Safe retry controls"/><div className="mt-4 grid gap-3">{data.deadLetters.map(job=><div key={job.id} className="rounded-lg border border-danger/30 p-3"><p className="font-semibold">{job.sources?.name||job.source_id}</p><p className="mt-1 text-xs text-danger">{job.error_summary||"No failure detail"}</p><button onClick={()=>action.mutate({path:`/admin/dead-letters/${job.id}/retry`,body:{reason:"Operator reviewed dead-letter failure and requested a controlled retry."}})} className="mt-3 text-sm font-semibold text-accent">Retry dead letter</button></div>)}</div>{!data.deadLetters.length?<EmptyState title="Dead-letter queue is clear" body="Exhausted scanner jobs will remain here for reviewed retry."/>:null}<details className="mt-4"><summary className="cursor-pointer font-semibold">Recent scan logs, failed URLs, billing events, and application errors</summary><pre className="mt-2 max-h-80 overflow-auto rounded bg-panel-strong p-3 text-xs">{JSON.stringify({scanJobs:data.scanJobs.slice(0,20),failedUrls:data.failedUrls,billingFailures:data.billingFailures,applicationErrors:data.applicationErrors},null,2)}</pre></details></Panel>
      <Panel><SectionHeader title="Support requests" eyebrow="Tracked resolution"/><div className="mt-4 grid gap-3">{data.supportRequests.map(ticket=><form key={ticket.id} onSubmit={event=>{event.preventDefault();const f=new FormData(event.currentTarget);action.mutate({path:`/admin/support/${ticket.id}`,method:"PUT",body:{status:f.get("status"),priority:f.get("priority"),resolution:f.get("resolution"),reason:f.get("resolution")}})}} className="rounded-lg border border-line p-3"><p className="font-semibold">{ticket.subject}</p><p className="mt-1 text-xs text-muted">{ticket.profiles?.email||ticket.user_id} · {ticket.message}</p><div className="mt-3 grid gap-2 sm:grid-cols-3"><Select name="status" values={["reviewing","resolved","closed"]}/><Select name="priority" values={["low","normal","high","urgent"]}/><TextInput name="resolution" required placeholder="Resolution / reason"/></div><SubmitButton disabled={action.isPending}>Update request</SubmitButton></form>)}</div>{!data.supportRequests.length?<EmptyState title="Support queue is clear" body="Open support requests will appear here."/>:null}</Panel>
      <Panel><SectionHeader title="Feature flags" eyebrow="Owner-only rollout controls"/><FeatureFlags flags={data.featureFlags} owner={data.admin.role==="owner"} run={action.mutate} pending={action.isPending}/></Panel>
    </div>
    <Panel className="mt-5"><SectionHeader title="Immutable audit log" eyebrow="Actor · target · reason · correlation"/><div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="text-muted"><tr><th className="p-2">Time</th><th className="p-2">Actor</th><th className="p-2">Action</th><th className="p-2">Target</th><th className="p-2">Reason</th><th className="p-2">Correlation</th></tr></thead><tbody>{data.auditLogs.map(row=><tr key={row.id} className="border-t border-line"><td className="p-2">{formatDate(row.created_at)}</td><td className="p-2">{row.actor_role}</td><td className="p-2">{row.action}</td><td className="p-2">{row.target_type}:{row.target_id}</td><td className="max-w-sm p-2 text-muted">{row.reason}</td><td className="p-2 font-mono text-xs">{row.correlation_id}</td></tr>)}</tbody></table></div></Panel>
  </AppShell>;
}
function SourceCreate({run,pending}:{run:(a:Action)=>void;pending:boolean}){return <form className="mt-4 grid gap-2 sm:grid-cols-2" onSubmit={event=>{event.preventDefault();const f=new FormData(event.currentTarget);run({path:"/admin/sources",body:{name:f.get("name"),baseUrl:f.get("baseUrl"),sourceType:"publisher",accessMethod:f.get("accessMethod"),requiresAttribution:true,attributionText:f.get("attributionText"),reason:f.get("reason")}})}}><TextInput name="name" required placeholder="Source name"/><TextInput name="baseUrl" type="url" required placeholder="https://sponsor.example/feed"/><Select name="accessMethod" values={["rss","atom","json_api","structured_html","admin_url","admin_import"]}/><TextInput name="attributionText" required placeholder="Attribution"/><TextInput name="reason" required placeholder="Registration reason"/><SubmitButton disabled={pending}><Database size={15}/>Create disabled source</SubmitButton></form>}
function SourceRow({source,failureRate,run,pending}:{source:any;failureRate?:{sampleSize:number;failures:number;rate:number};run:(a:Action)=>void;pending:boolean}){return <form onSubmit={event=>{event.preventDefault();const f=new FormData(event.currentTarget);run({path:`/admin/sources/${source.id}`,method:"PUT",body:{scanFrequencyMinutes:Number(f.get("cadence")),rateLimitPerMinute:Number(f.get("rate")),robotsPolicyStatus:f.get("robots"),termsReviewStatus:f.get("terms"),requiresAttribution:true,attributionText:f.get("attribution"),scanEnabled:f.get("enabled")==="true",reason:f.get("reason")}})}} className="rounded-lg border border-line p-3"><div className="flex items-center justify-between gap-2"><p className="font-semibold">{source.name}</p><Badge tone={source.scan_enabled?"ok":"warn"}>{source.health_status}</Badge></div><p className="mt-1 break-all text-xs text-muted">{source.base_url}</p><p className="mt-1 text-xs text-muted">Recent scan failure rate: {((failureRate?.rate??0)*100).toFixed(1)}% ({failureRate?.failures??0}/{failureRate?.sampleSize??0})</p><div className="mt-3 grid gap-2 sm:grid-cols-3"><TextInput name="cadence" type="number" min={5} defaultValue={source.scan_frequency_minutes}/><TextInput name="rate" type="number" min={1} defaultValue={source.rate_limit_per_minute}/><TextInput name="attribution" defaultValue={source.attribution_text||""}/><Select name="robots" values={["pending","approved","restricted","prohibited"]} defaultValue={source.robots_policy_status}/><Select name="terms" values={["pending","approved","restricted","prohibited"]} defaultValue={source.terms_review_status}/><Select name="enabled" values={["false","true"]} defaultValue={String(source.scan_enabled)}/><TextInput name="reason" required placeholder="Change reason"/></div><div className="mt-3 flex gap-3"><SubmitButton disabled={pending}>Save source</SubmitButton><button type="button" onClick={()=>run({path:`/admin/sources/${source.id}/run`,body:{reason:"Administrator requested a manual policy-approved scan."}})} className="text-sm font-semibold text-accent"><Play size={14} className="mr-1 inline"/>Run scan</button></div></form>}
function ListingReview({listing,id,loading,run,pending}:{listing:any;id:string;loading:boolean;run:(a:Action)=>void;pending:boolean}){if(loading)return <LoadingState title="Loading listing evidence"/>;if(!listing)return null;return <div className="mt-5 rounded-xl border border-accent/30 p-4"><h3 className="font-semibold">{listing.title}</h3><p className="mt-1 text-xs text-muted">{listing.official_url}</p><details className="mt-3"><summary className="cursor-pointer text-sm font-semibold">AI field evidence, rules versions, and change history</summary><pre className="mt-2 max-h-72 overflow-auto rounded bg-panel-strong p-3 text-xs">{JSON.stringify({evidence:listing.sweepstakes_field_evidence,rules:listing.sweepstakes_rules_versions,changes:listing.sweepstakes_change_events,merges:listing.sweepstakes_merge_events},null,2)}</pre></details><form className="mt-3 grid gap-2 sm:grid-cols-2" onSubmit={event=>{event.preventDefault();const f=new FormData(event.currentTarget);run({path:`/admin/listings/${id}`,method:"PUT",body:{fields:{title:f.get("title"),sponsor_name:f.get("sponsor"),source_confidence_score:Number(f.get("confidence"))},reason:f.get("reason")}})}}><TextInput name="title" defaultValue={listing.title}/><TextInput name="sponsor" defaultValue={listing.sponsor_name}/><TextInput name="confidence" type="number" min={0} max={100} defaultValue={listing.source_confidence_score}/><TextInput name="reason" required placeholder="Correction reason"/><SubmitButton disabled={pending}>Save correction</SubmitButton></form><form className="mt-3 flex flex-wrap gap-2" onSubmit={event=>event.preventDefault()}>{["approve","reject","suspicious","expired","canceled"].map(decision=><button key={decision} onClick={()=>{const reason=prompt(`Reason for ${decision}`);if(reason)run({path:`/admin/listings/${id}/decision`,body:{decision,reason}})}} className="rounded-md border border-line px-3 py-2 text-sm">{titleCase(decision)}</button>)}</form><form className="mt-3 grid gap-2 sm:grid-cols-3" onSubmit={event=>{event.preventDefault();const f=new FormData(event.currentTarget);run({path:"/admin/listings/merge",body:{targetId:id,sourceId:f.get("sourceId"),reason:f.get("reason")}})}}><TextInput name="sourceId" required placeholder="Duplicate source listing UUID"/><TextInput name="reason" required placeholder="Merge reason"/><SubmitButton disabled={pending}>Merge duplicate</SubmitButton></form>{listing.sweepstakes_merge_events?.filter((x:any)=>x.status==="applied").map((merge:any)=><button key={merge.id} onClick={()=>run({path:`/admin/merges/${merge.id}/undo`,body:{reason:"Administrator reviewed merge evidence and requested reversal."}})} className="mt-3 text-sm font-semibold text-warning">Undo merge {merge.id.slice(0,8)}</button>)}</div>}
function UserRow({user,ledger,owner,run,pending}:{user:any;ledger:any[];owner:boolean;run:(a:Action)=>void;pending:boolean}){return <div className="rounded-lg border border-line p-3"><div className="flex justify-between gap-2"><div><p className="font-semibold">{user.display_name}</p><p className="text-xs text-muted">{user.email} · {user.subscriptions?.[0]?.plan_key||"free_flight"}</p></div><Badge tone={user.account_disabled_at?"danger":"ok"}>{user.account_disabled_at?"disabled":user.platform_role}</Badge></div><details className="mt-2"><summary className="cursor-pointer text-xs font-semibold text-accent">View credit ledger ({ledger.length})</summary><pre className="mt-2 max-h-48 overflow-auto rounded bg-panel-strong p-2 text-xs">{JSON.stringify(ledger,null,2)}</pre></details><form className="mt-3 grid gap-2 sm:grid-cols-3" onSubmit={event=>{event.preventDefault();const f=new FormData(event.currentTarget);run({path:`/admin/users/${user.id}/credits`,body:{amount:Number(f.get("amount")),reason:f.get("reason"),idempotencyKey:crypto.randomUUID()}})}}><TextInput name="amount" type="number" required placeholder="+ grant / - correction"/><TextInput name="reason" required placeholder="Credit reason"/><SubmitButton disabled={pending}>Adjust credits</SubmitButton></form>{owner?<button onClick={()=>{const reason=prompt(user.account_disabled_at?"Reason to enable account":"Reason to disable abusive account");if(reason)run({path:`/admin/users/${user.id}/disable`,body:{disabled:!user.account_disabled_at,reason}})}} className="mt-3 text-sm font-semibold text-danger">{user.account_disabled_at?"Enable account":"Disable account"}</button>:null}</div>}
function FeatureFlags({flags,owner,run,pending}:{flags:any[];owner:boolean;run:(a:Action)=>void;pending:boolean}){return <div className="mt-4 grid gap-3">{flags.map(flag=><form key={flag.key} onSubmit={event=>{event.preventDefault();const f=new FormData(event.currentTarget);run({path:`/admin/feature-flags/${flag.key}`,method:"PUT",body:{enabled:f.get("enabled")==="on",description:f.get("description"),reason:f.get("reason")}})}} className="rounded-lg border border-line p-3"><label className="flex gap-2 font-semibold"><input name="enabled" type="checkbox" defaultChecked={flag.enabled} disabled={!owner}/>{flag.key}</label><TextInput name="description" defaultValue={flag.description}/><TextInput name="reason" required placeholder="Rollout reason"/><SubmitButton disabled={!owner||pending}>Update flag</SubmitButton></form>)}{owner?<form onSubmit={event=>{event.preventDefault();const f=new FormData(event.currentTarget);run({path:`/admin/feature-flags/${f.get("key")}`,method:"PUT",body:{enabled:false,description:f.get("description"),reason:f.get("reason")}})}} className="grid gap-2 sm:grid-cols-3"><TextInput name="key" required placeholder="feature.key"/><TextInput name="description" required placeholder="Description"/><TextInput name="reason" required placeholder="Creation reason"/><SubmitButton disabled={pending}><Flag size={14}/>Create disabled flag</SubmitButton></form>:<p className="text-sm text-muted">Feature flag mutations require platform-owner access.</p>}</div>}
function Select({name,values,defaultValue}:{name:string;values:string[];defaultValue?:string}){return <select name={name} defaultValue={defaultValue??values[0]} className="h-10 rounded-md border border-line bg-panel-strong px-3 text-sm">{values.map(value=><option key={value} value={value}>{titleCase(value)}</option>)}</select>}
