import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BellRing, CheckCheck, Clock3, Mail, Play, Radar, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Link } from "wouter";
import { AppShell } from "@/components/app-shell";
import { EmptyState, ErrorNotice, LoadingState, SectionHeader } from "@/components/dashboard-kit";
import { Badge, MetricCard, PageHeader, Panel, SubmitButton, TextInput } from "@/components/ui";
import { apiGet, apiSend } from "@/lib/api";
import { formatDate, titleCase } from "@/lib/format";
import type { AlertsSummary } from "@/lib/types";

export default function AlertsPage(){
  const qc=useQueryClient();
  const query=useQuery({queryKey:["alerts"],queryFn:()=>apiGet<AlertsSummary>("/alerts")});
  const refresh=()=>void qc.invalidateQueries({queryKey:["alerts"]});
  const action=useMutation({mutationFn:({path,method="POST",body={}}:{path:string;method?:"POST"|"PUT"|"DELETE";body?:Record<string,unknown>})=>apiSend(path,method,body),onSuccess:()=>{refresh();toast.success("Monitoring updated");},onError:(error)=>toast.error(error.message)});
  const data=query.data;
  return <AppShell>
    <PageHeader title="Alerts & Custom Scans" kicker="Ongoing opportunity monitoring" description="Receive time-aware flight briefings, track changes, and run plan-gated searches across approved public sources." />
    {query.isLoading?<LoadingState title="Loading monitoring systems"/>:null}
    {query.isError?<ErrorNotice title="Alerts unavailable" body="The monitoring service could not be loaded."/>:null}
    {data?<><div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Unread alerts" value={data.unreadCount} sublabel="In-app notifications"/><MetricCard label="Pilot Credits" value={data.creditBalance} sublabel={`${data.customScanCost} per custom scan`}/><MetricCard label="Custom scanners" value={data.customScanners.length} sublabel={`${data.customScanPolicy.maxProfiles} allowed on ${titleCase(data.planKey)}`}/><MetricCard label="Email delivery" value={data.emailProvider==="resend"?"Ready":"Off"} sublabel="Requires explicit provider configuration"/></div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(22rem,.75fr)]">
      <div className="grid gap-5">
        <Panel><div className="flex flex-wrap items-center justify-between gap-3"><SectionHeader title="Flight alerts" eyebrow="Duplicate-safe monitoring"/><button type="button" onClick={()=>action.mutate({path:"/alerts/read-all"})} className="inline-flex min-h-10 items-center gap-2 rounded-md border border-line px-3 text-sm"><CheckCheck size={16}/>Mark all read</button></div>
          <div className="mt-4 grid gap-3">{data.notifications.map(item=><article key={item.id} className={`rounded-xl border p-4 ${item.read_at?"border-line bg-panel-strong/45":"border-accent/35 bg-accent/5"}`}><div className="flex items-start gap-3"><span className="mt-0.5 rounded-lg bg-accent/12 p-2 text-accent"><BellRing size={17}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{item.title}</h3><Badge tone={item.priority>=80?"warn":"default"}>{titleCase(item.type)}</Badge>{!item.read_at?<Badge tone="ok">New</Badge>:null}</div><p className="mt-1 text-sm leading-6 text-muted">{item.body}</p><p className="mt-2 text-xs text-muted">{formatDate(item.created_at)}</p></div>{!item.read_at?<button aria-label={`Mark ${item.title} read`} onClick={()=>action.mutate({path:`/alerts/${item.id}/read`})} className="text-muted hover:text-accent"><CheckCheck size={17}/></button>:null}</div></article>)}</div>
          {!data.notifications.length?<EmptyState title="Radar is quiet" body="New matches, ending opportunities, schedule reminders, rules changes, scan results, credit warnings, and billing issues will appear here."/>:null}
        </Panel>
        <Panel><SectionHeader title="Custom scanner profiles" eyebrow="Approved sources only"/>
          {!data.customScanPolicy.enabled?<div className="rounded-xl border border-reward/30 bg-reward/10 p-4"><p className="font-semibold">Ace Pilot or Squadron required</p><p className="mt-1 text-sm text-muted">Custom scans consume {data.customScanCost} Pilot Credits and never enter promotions.</p><Link href="/dashboard/billing" className="mt-3 inline-flex text-sm font-semibold text-reward">Review upgrade options</Link></div>:<form className="grid gap-3 md:grid-cols-2" onSubmit={(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);action.mutate({path:"/custom-scanners",body:{name:form.get("name"),filters:{keywords:form.get("keywords"),sponsor:form.get("sponsor"),minimumValue:Number(form.get("minimumValue")||0),category:form.get("category"),country:form.get("country")},sourceIds:form.getAll("sourceIds"),cadenceMinutes:Number(form.get("cadenceMinutes"))}});event.currentTarget.reset();}}><TextInput name="name" required maxLength={120} placeholder="Scanner name"/><TextInput name="keywords" placeholder="Keywords"/><TextInput name="sponsor" placeholder="Sponsor"/><TextInput name="category" placeholder="Prize category"/><TextInput name="minimumValue" type="number" min={0} placeholder="Minimum prize value"/><TextInput name="country" maxLength={2} placeholder="Country code"/><label className="grid gap-1 text-xs font-semibold uppercase tracking-wide text-muted">Cadence<select name="cadenceMinutes" defaultValue={data.customScanPolicy.minimumCadenceMinutes} className="h-10 rounded-md border border-line bg-panel-strong px-3 text-sm text-foreground"><option value={data.customScanPolicy.minimumCadenceMinutes}>Plan minimum ({data.customScanPolicy.minimumCadenceMinutes/60}h)</option><option value={43200}>Monthly</option></select></label><fieldset className="rounded-lg border border-line p-3 md:col-span-2"><legend className="px-1 text-xs font-semibold uppercase tracking-wide text-muted">Approved sources</legend><div className="grid gap-2 sm:grid-cols-2">{data.approvedSources.map(source=><label key={source.id} className="flex gap-2 text-sm"><input type="checkbox" name="sourceIds" value={source.id} className="accent-accent"/><span>{source.name}<small className="block text-muted">{source.attribution_text||"Public source"}</small></span></label>)}</div>{!data.approvedSources.length?<p className="text-sm text-muted">No source is both enabled and policy-approved.</p>:null}</fieldset><SubmitButton disabled={action.isPending||!data.approvedSources.length}><Radar size={16}/>Create scanner</SubmitButton></form>}
          <div className="mt-5 grid gap-3">{data.customScanners.map(scanner=><article key={scanner.id} className="rounded-xl border border-line p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{scanner.name}</h3><p className="mt-1 text-sm text-muted">{String(scanner.filters.keywords||"Any keyword")} · every {scanner.cadence_minutes/60}h · next {formatDate(scanner.next_run_at)}</p></div><div className="flex gap-2"><button aria-label={`Run ${scanner.name}`} onClick={()=>action.mutate({path:`/custom-scanners/${scanner.id}/run`})} className="rounded-md border border-line p-2 text-accent"><Play size={16}/></button><button aria-label={`Delete ${scanner.name}`} onClick={()=>action.mutate({path:`/custom-scanners/${scanner.id}`,method:"DELETE"})} className="rounded-md border border-line p-2 text-danger"><Trash2 size={16}/></button></div></div></article>)}</div>
        </Panel>
      </div>
      <div className="grid content-start gap-5">
        <Panel><SectionHeader title="Briefing preferences" eyebrow="Timezone-aware delivery"/><form className="grid gap-3" onSubmit={(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);const checked=(name:string)=>form.get(name)==="on";action.mutate({path:"/alerts/preferences",method:"PUT",body:{inAppEnabled:checked("inAppEnabled"),emailEnabled:checked("emailEnabled"),dailyDigestEnabled:checked("dailyDigestEnabled"),weeklyDigestEnabled:checked("weeklyDigestEnabled"),endingSoonEnabled:checked("endingSoonEnabled"),highValueEnabled:checked("highValueEnabled"),recommendationsEnabled:checked("recommendationsEnabled"),entryRemindersEnabled:checked("entryRemindersEnabled")}});}}>{[["inAppEnabled","In-app notifications"],["emailEnabled","Email notifications"],["dailyDigestEnabled","Daily digest at 8:00 local time"],["weeklyDigestEnabled","Weekly Monday briefing"],["endingSoonEnabled","Ending-soon alerts"],["highValueEnabled","High-value opportunities"],["recommendationsEnabled","Personalized recommendations"],["entryRemindersEnabled","User-reported entry reminders"]].map(([name,label])=><label key={name} className="flex min-h-10 items-center gap-3 rounded-md border border-line px-3 text-sm"><input name={name} type="checkbox" defaultChecked={Boolean(data.preferences[name as keyof typeof data.preferences])} className="accent-accent"/>{label}</label>)}<SubmitButton disabled={action.isPending}>Save preferences</SubmitButton></form><p className="mt-3 text-xs leading-5 text-muted"><Mail size={14} className="mr-1 inline"/>Email is opt-in and provider delivery stays disabled until server configuration is complete.</p></Panel>
        <Panel><SectionHeader title="Recent scan runs" eyebrow="Auditable summaries"/><p className="mb-3 text-xs leading-5 text-muted">Verify sponsor rules and eligibility on the official site before taking any action. Play Pack Pilot never submits entries.</p><div className="grid gap-3">{data.customScanRuns.map(run=><div key={run.id} className="rounded-lg border border-line p-3"><div className="flex items-center justify-between gap-2"><Badge tone={run.status==="completed"?"ok":run.status==="failed"?"danger":"warn"}>{titleCase(run.status)}</Badge><span className="text-xs text-muted">{formatDate(run.created_at)}</span></div><p className="mt-2 text-sm">{run.match_count} matching opportunities</p>{run.error_message?<p className="mt-1 text-xs text-danger">{run.error_message}</p>:null}</div>)}</div>{!data.customScanRuns.length?<EmptyState title="No scan runs yet" body="Scheduled and manual custom scans will retain their approved sources, filters, results, and credit reference." action={<Clock3 className="text-accent"/>}/>:null}</Panel>
      </div>
    </div></>:null}
  </AppShell>;
}
