import { Check, PlaneTakeoff, ShieldCheck } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "wouter";
import { ErrorNotice, LoadingState } from "@/components/dashboard-kit";
import { apiGet } from "@/lib/api";
import type { BillingCatalogPlan } from "@/lib/types";

export default function PricingPage(){const catalog=useQuery({queryKey:["billing-catalog"],queryFn:()=>apiGet<BillingCatalogPlan[]>("/billing/catalog")});return <main className="min-h-dvh bg-background px-4 py-10 text-foreground sm:px-6"><div className="mx-auto max-w-6xl"><div className="flex items-center justify-between"><Link href="/" className="font-display text-lg font-extrabold">Play Pack Pilot</Link><Link href="/login" className="rounded-full border border-line px-4 py-2 text-sm">Log in</Link></div><header className="mx-auto max-w-3xl py-16 text-center"><p className="text-xs font-bold uppercase tracking-[.2em] text-accent">Choose your altitude</p><h1 className="mt-4 text-balance font-display text-4xl font-extrabold sm:text-6xl">Software access and AI capacity—never entries or odds.</h1><p className="mt-5 text-pretty text-muted">Start free, then upgrade for deeper analysis, alerts, and processing capacity. Annual plans are billed by Stripe in test mode until launch authorization.</p></header>{catalog.isLoading?<LoadingState title="Loading the flight catalog"/>:null}{catalog.isError?<ErrorNotice title="Pricing unavailable" body="The trusted server catalog could not be loaded."/>:null}{catalog.data?<div className="grid gap-4 lg:grid-cols-4">{catalog.data.map((plan)=><article key={plan.key} className={`flex flex-col rounded-2xl border p-5 ${plan.key==="co_pilot"?"border-reward bg-reward/5":"border-line bg-panel"}`}><h2 className="text-xl font-bold">{plan.name}</h2><p className="mt-2 min-h-12 text-sm text-muted">{plan.description}</p><p className="mt-5 text-3xl font-bold">{money(plan.monthlyPriceCents)}<span className="text-sm font-normal text-muted"> /mo</span></p>{plan.annualPriceCents?<p className="mt-1 text-sm text-accent">{money(plan.annualPriceCents)} annually</p>:<p className="mt-1 text-sm text-accent">No payment method required</p>}<p className="mt-4 font-semibold text-reward">{plan.monthlyCredits.toLocaleString()} Pilot Credits monthly</p><ul className="mt-5 grid gap-2 text-sm">{features(plan).map((feature)=><li key={feature} className="flex gap-2"><Check size={15} className="mt-0.5 shrink-0 text-ok"/>{feature}</li>)}</ul><Link href="/signup" className="mt-7 inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-accent px-4 text-sm font-bold text-[#08110e]"><PlaneTakeoff size={16}/>Start Scanning</Link></article>)}</div>:null}<p className="mx-auto mt-8 flex max-w-3xl items-start justify-center gap-2 text-center text-xs leading-5 text-muted"><ShieldCheck size={16} className="shrink-0 text-accent"/>Pilot Credits are non-transferable internal usage units with no cash or prize value. They cannot purchase entries, fund prizes, improve odds, or be withdrawn.</p></div></main>;}
function money(cents:number){return cents===0?"$0":`$${(cents/100).toFixed(2)}`;}
function features(plan:BillingCatalogPlan){const f=plan.features;return[f.full_feed?"Full opportunity feed":"Limited opportunity feed",Number(f.saved_items)===-1?"Unlimited saves":`Save up to ${f.saved_items}`,f.deep_ai?"Deep AI analysis":"Standard analysis",Number(f.household_profiles)>1?`${f.household_profiles} household profiles`:f.digest_daily?"Daily digest":"Weekly digest",f.custom_scans?`${f.custom_scans} custom scans`:"Standard reminders and tracking"].filter(Boolean) as string[];}
