CREATE TYPE subscription_plan AS ENUM ('free_flight','co_pilot','ace_pilot','squadron');
CREATE TYPE subscription_status AS ENUM ('none','incomplete','trialing','active','past_due','unpaid','paused','canceled');
CREATE TYPE billing_event_status AS ENUM ('processing','processed','failed','ignored');
CREATE TYPE credit_entry_type AS ENUM ('grant','consume','refund','adjustment');

CREATE TABLE billing_customers (user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE RESTRICT, provider text NOT NULL DEFAULT 'stripe', provider_customer_id text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT billing_customers_pk PRIMARY KEY(user_id,provider), CONSTRAINT billing_customers_provider_id_unique UNIQUE(provider,provider_customer_id));
CREATE TABLE subscriptions (user_id uuid PRIMARY KEY REFERENCES profiles(id) ON DELETE RESTRICT, provider_subscription_id text UNIQUE, provider_price_id text, plan_key subscription_plan NOT NULL DEFAULT 'free_flight', status subscription_status NOT NULL DEFAULT 'none', current_period_start timestamptz, current_period_end timestamptz, cancel_at_period_end boolean NOT NULL DEFAULT false, trial_end timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX subscriptions_status_idx ON subscriptions(status,current_period_end);
CREATE TABLE entitlements (user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, feature_key text NOT NULL, limit_value integer, active_from timestamptz NOT NULL DEFAULT now(), active_until timestamptz, source text NOT NULL, updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT entitlements_pk PRIMARY KEY(user_id,feature_key,source));
CREATE INDEX entitlements_active_idx ON entitlements(user_id,active_until);
CREATE TABLE billing_events (provider_event_id text PRIMARY KEY, user_id uuid REFERENCES profiles(id) ON DELETE SET NULL, event_type text NOT NULL, status billing_event_status NOT NULL DEFAULT 'processing', received_at timestamptz NOT NULL DEFAULT now(), processed_at timestamptz, error_message text, metadata jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE INDEX billing_events_user_idx ON billing_events(user_id,received_at DESC);
CREATE INDEX billing_events_status_idx ON billing_events(status,received_at);
CREATE TABLE credit_ledger (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE RESTRICT, amount integer NOT NULL CHECK(amount <> 0), entry_type credit_entry_type NOT NULL, reason_code text NOT NULL, source_reference text NOT NULL, idempotency_key text NOT NULL UNIQUE, expires_at timestamptz, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT credit_ledger_type_sign CHECK ((entry_type='consume' AND amount<0) OR (entry_type<>'consume' AND amount>0)));
CREATE INDEX credit_ledger_balance_idx ON credit_ledger(user_id,expires_at,created_at DESC);

ALTER TABLE billing_customers ENABLE ROW LEVEL SECURITY; ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY; ALTER TABLE entitlements ENABLE ROW LEVEL SECURITY; ALTER TABLE billing_events ENABLE ROW LEVEL SECURITY; ALTER TABLE credit_ledger ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN IF to_regprocedure('auth.uid()') IS NOT NULL THEN
  CREATE POLICY billing_customers_read_own ON billing_customers FOR SELECT TO authenticated USING(user_id=auth.uid());
  CREATE POLICY subscriptions_read_own ON subscriptions FOR SELECT TO authenticated USING(user_id=auth.uid());
  CREATE POLICY entitlements_read_own ON entitlements FOR SELECT TO authenticated USING(user_id=auth.uid());
  CREATE POLICY billing_events_read_own ON billing_events FOR SELECT TO authenticated USING(user_id=auth.uid());
  CREATE POLICY credit_ledger_read_own ON credit_ledger FOR SELECT TO authenticated USING(user_id=auth.uid());
END IF; END $$;

CREATE OR REPLACE FUNCTION pilot_credit_balance(p_user_id uuid) RETURNS bigint LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT coalesce(sum(amount),0)::bigint FROM credit_ledger WHERE user_id=p_user_id AND (expires_at IS NULL OR expires_at>now()) $$;
CREATE OR REPLACE FUNCTION grant_pilot_credits(p_user_id uuid,p_amount integer,p_reason_code text,p_source_reference text,p_idempotency_key text,p_expires_at timestamptz DEFAULT NULL,p_metadata jsonb DEFAULT '{}'::jsonb) RETURNS TABLE(entry_id uuid,balance bigint,applied boolean) LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE v_id uuid; BEGIN IF p_amount<=0 THEN RAISE EXCEPTION 'Credit grant must be positive'; END IF; PERFORM pg_advisory_xact_lock(hashtextextended(p_user_id::text,0)); SELECT id INTO v_id FROM credit_ledger WHERE idempotency_key=p_idempotency_key AND user_id=p_user_id; IF v_id IS NOT NULL THEN RETURN QUERY SELECT v_id,pilot_credit_balance(p_user_id),false; RETURN; END IF; INSERT INTO credit_ledger(user_id,amount,entry_type,reason_code,source_reference,idempotency_key,expires_at,metadata) VALUES(p_user_id,p_amount,'grant',p_reason_code,p_source_reference,p_idempotency_key,p_expires_at,p_metadata) RETURNING id INTO v_id; RETURN QUERY SELECT v_id,pilot_credit_balance(p_user_id),true; END $$;
CREATE OR REPLACE FUNCTION consume_pilot_credits(p_user_id uuid,p_amount integer,p_reason_code text,p_source_reference text,p_idempotency_key text,p_metadata jsonb DEFAULT '{}'::jsonb) RETURNS TABLE(entry_id uuid,balance bigint,applied boolean) LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE v_id uuid; v_balance bigint; BEGIN IF p_amount<=0 THEN RAISE EXCEPTION 'Credit cost must be positive'; END IF; PERFORM pg_advisory_xact_lock(hashtextextended(p_user_id::text,0)); SELECT id INTO v_id FROM credit_ledger WHERE idempotency_key=p_idempotency_key AND user_id=p_user_id; IF v_id IS NOT NULL THEN RETURN QUERY SELECT v_id,pilot_credit_balance(p_user_id),false; RETURN; END IF; v_balance:=pilot_credit_balance(p_user_id); IF v_balance<p_amount THEN RAISE EXCEPTION 'INSUFFICIENT_PILOT_CREDITS' USING ERRCODE='P0001'; END IF; INSERT INTO credit_ledger(user_id,amount,entry_type,reason_code,source_reference,idempotency_key,metadata) VALUES(p_user_id,-p_amount,'consume',p_reason_code,p_source_reference,p_idempotency_key,p_metadata) RETURNING id INTO v_id; RETURN QUERY SELECT v_id,pilot_credit_balance(p_user_id),true; END $$;
CREATE OR REPLACE FUNCTION refund_pilot_credits(p_user_id uuid,p_charge_idempotency_key text,p_refund_idempotency_key text,p_metadata jsonb DEFAULT '{}'::jsonb) RETURNS TABLE(entry_id uuid,balance bigint,applied boolean) LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE v_id uuid; v_amount integer; v_source text; BEGIN PERFORM pg_advisory_xact_lock(hashtextextended(p_user_id::text,0)); SELECT id INTO v_id FROM credit_ledger WHERE idempotency_key=p_refund_idempotency_key AND user_id=p_user_id; IF v_id IS NOT NULL THEN RETURN QUERY SELECT v_id,pilot_credit_balance(p_user_id),false; RETURN; END IF; SELECT -amount,source_reference INTO v_amount,v_source FROM credit_ledger WHERE user_id=p_user_id AND idempotency_key=p_charge_idempotency_key AND entry_type='consume'; IF v_amount IS NULL THEN RAISE EXCEPTION 'Credit charge was not found'; END IF; INSERT INTO credit_ledger(user_id,amount,entry_type,reason_code,source_reference,idempotency_key,metadata) VALUES(p_user_id,v_amount,'refund','failed_action_refund',v_source,p_refund_idempotency_key,p_metadata) RETURNING id INTO v_id; RETURN QUERY SELECT v_id,pilot_credit_balance(p_user_id),true; END $$;
CREATE OR REPLACE FUNCTION claim_billing_event(p_provider_event_id text,p_event_type text,p_metadata jsonb DEFAULT '{}'::jsonb) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN INSERT INTO billing_events(provider_event_id,event_type,status,metadata) VALUES(p_provider_event_id,p_event_type,'processing',p_metadata) ON CONFLICT(provider_event_id) DO UPDATE SET status='processing',error_message=NULL WHERE billing_events.status='failed'; RETURN FOUND; END $$;
REVOKE ALL ON FUNCTION pilot_credit_balance(uuid),grant_pilot_credits(uuid,integer,text,text,text,timestamptz,jsonb),consume_pilot_credits(uuid,integer,text,text,text,jsonb),refund_pilot_credits(uuid,text,text,jsonb),claim_billing_event(text,text,jsonb) FROM PUBLIC;
