-- Phase 9 is additive. Notifications monitor opportunities; they never submit entries or open inbox links.
CREATE TYPE notification_type AS ENUM ('high_match','ending_soon','entry_due','rules_changed','deadline_changed','opportunity_canceled','source_confidence_reduced','custom_scan_completed','credits_low','payment_failed');
CREATE TYPE notification_channel AS ENUM ('in_app','email','browser_push','sms','mobile_push');
CREATE TYPE notification_delivery_status AS ENUM ('pending','processing','delivered','failed','skipped');
CREATE TYPE digest_kind AS ENUM ('daily','weekly','ending_soon','high_value','recommendations','entry_reminders');
CREATE TYPE custom_scan_status AS ENUM ('queued','running','completed','partial','failed','canceled');

CREATE TABLE notification_preferences(user_id uuid PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,in_app_enabled boolean NOT NULL DEFAULT true,email_enabled boolean NOT NULL DEFAULT false,daily_digest_enabled boolean NOT NULL DEFAULT false,weekly_digest_enabled boolean NOT NULL DEFAULT true,ending_soon_enabled boolean NOT NULL DEFAULT true,high_value_enabled boolean NOT NULL DEFAULT true,recommendations_enabled boolean NOT NULL DEFAULT true,entry_reminders_enabled boolean NOT NULL DEFAULT true,email_unsubscribed_at timestamptz,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE notifications(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,type notification_type NOT NULL,title text NOT NULL,body text NOT NULL,sweepstakes_id uuid REFERENCES sweepstakes(id) ON DELETE SET NULL,source_reference text NOT NULL,dedupe_key text NOT NULL,priority integer NOT NULL DEFAULT 0 CHECK(priority BETWEEN 0 AND 100),read_at timestamptz,metadata jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(user_id,dedupe_key));
CREATE INDEX notifications_user_unread_idx ON notifications(user_id,read_at,created_at DESC);
CREATE TABLE notification_deliveries(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),notification_id uuid NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,channel notification_channel NOT NULL,status notification_delivery_status NOT NULL DEFAULT 'pending',attempt_count integer NOT NULL DEFAULT 0 CHECK(attempt_count>=0),provider_message_id text,scheduled_at timestamptz NOT NULL DEFAULT now(),attempted_at timestamptz,delivered_at timestamptz,next_retry_at timestamptz,error_message text,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(notification_id,channel));
CREATE INDEX notification_deliveries_due_idx ON notification_deliveries(status,next_retry_at,scheduled_at);
CREATE TABLE digest_runs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,kind digest_kind NOT NULL,window_start timestamptz NOT NULL,window_end timestamptz NOT NULL,status notification_delivery_status NOT NULL DEFAULT 'pending',item_count integer NOT NULL DEFAULT 0 CHECK(item_count>=0),error_message text,created_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,UNIQUE(user_id,kind,window_start));
CREATE TABLE custom_scanners(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,name text NOT NULL CHECK(char_length(name) BETWEEN 1 AND 120),filters jsonb NOT NULL DEFAULT '{}'::jsonb CHECK(jsonb_typeof(filters)='object'),source_ids uuid[] NOT NULL CHECK(cardinality(source_ids) BETWEEN 1 AND 25),cadence_minutes integer NOT NULL CHECK(cadence_minutes BETWEEN 60 AND 43200),enabled boolean NOT NULL DEFAULT true,next_run_at timestamptz NOT NULL,last_run_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(user_id,name));
CREATE INDEX custom_scanners_due_idx ON custom_scanners(enabled,next_run_at);
CREATE TABLE custom_scan_runs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),custom_scanner_id uuid NOT NULL REFERENCES custom_scanners(id) ON DELETE CASCADE,user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,status custom_scan_status NOT NULL DEFAULT 'queued',scheduled_for timestamptz NOT NULL,started_at timestamptz,completed_at timestamptz,source_ids uuid[] NOT NULL,result_summary jsonb NOT NULL DEFAULT '{}'::jsonb,match_count integer NOT NULL DEFAULT 0 CHECK(match_count>=0),credit_idempotency_key text NOT NULL UNIQUE,error_message text,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX custom_scan_runs_user_created_idx ON custom_scan_runs(user_id,created_at DESC);

ALTER TABLE notification_preferences ENABLE ROW LEVEL SECURITY; ALTER TABLE notifications ENABLE ROW LEVEL SECURITY; ALTER TABLE notification_deliveries ENABLE ROW LEVEL SECURITY; ALTER TABLE digest_runs ENABLE ROW LEVEL SECURITY; ALTER TABLE custom_scanners ENABLE ROW LEVEL SECURITY; ALTER TABLE custom_scan_runs ENABLE ROW LEVEL SECURITY;
CREATE POLICY notification_preferences_read_own ON notification_preferences FOR SELECT TO authenticated USING(user_id=auth.uid());
CREATE POLICY notifications_read_own ON notifications FOR SELECT TO authenticated USING(user_id=auth.uid());
CREATE POLICY notification_deliveries_read_own ON notification_deliveries FOR SELECT TO authenticated USING(EXISTS(SELECT 1 FROM notifications n WHERE n.id=notification_id AND n.user_id=auth.uid()));
CREATE POLICY digest_runs_read_own ON digest_runs FOR SELECT TO authenticated USING(user_id=auth.uid());
CREATE POLICY custom_scanners_read_own ON custom_scanners FOR SELECT TO authenticated USING(user_id=auth.uid());
CREATE POLICY custom_scan_runs_read_own ON custom_scan_runs FOR SELECT TO authenticated USING(user_id=auth.uid());
GRANT SELECT ON notification_preferences,notifications,notification_deliveries,digest_runs,custom_scanners,custom_scan_runs TO authenticated;
REVOKE INSERT,UPDATE,DELETE ON notification_preferences,notifications,notification_deliveries,digest_runs,custom_scanners,custom_scan_runs FROM authenticated,anon;

CREATE OR REPLACE FUNCTION generate_phase9_notifications(p_now timestamptz DEFAULT now()) RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE v_count integer:=0; v_rows integer; BEGIN
INSERT INTO notifications(user_id,type,title,body,sweepstakes_id,source_reference,dedupe_key,priority,metadata)
SELECT us.user_id,'ending_soon','Saved opportunity ending soon',s.title||' ends soon. Verify the official rules before visiting the sponsor site.',s.id,s.id::text,'ending:'||s.id||':'||to_char(s.end_at AT TIME ZONE 'UTC','YYYY-MM-DD'),70,jsonb_build_object('endAt',s.end_at,'officialUrl',s.official_url)
FROM user_saved_sweepstakes us JOIN sweepstakes s ON s.id=us.sweepstakes_id LEFT JOIN notification_preferences np ON np.user_id=us.user_id WHERE s.status='active' AND s.end_at>p_now AND s.end_at<=p_now+interval '48 hours' AND coalesce(np.ending_soon_enabled,true) ON CONFLICT DO NOTHING; GET DIAGNOSTICS v_rows=ROW_COUNT; v_count:=v_count+v_rows;
INSERT INTO notifications(user_id,type,title,body,sweepstakes_id,source_reference,dedupe_key,priority,metadata)
SELECT st.user_id,'entry_due','A repeat entry is available',s.title||' is due based on your user-reported schedule.',s.id,s.id::text,'entry-due:'||s.id||':'||to_char(st.next_entry_due_at AT TIME ZONE coalesce(p.timezone,'UTC'),'YYYY-MM-DD-HH24'),55,jsonb_build_object('nextEntryDueAt',st.next_entry_due_at)
FROM user_sweepstakes_status st JOIN sweepstakes s ON s.id=st.sweepstakes_id JOIN profiles p ON p.id=st.user_id LEFT JOIN notification_preferences np ON np.user_id=st.user_id WHERE st.next_entry_due_at<=p_now AND st.status IN('entered','enter_again') AND coalesce(np.entry_reminders_enabled,true) ON CONFLICT DO NOTHING; GET DIAGNOSTICS v_rows=ROW_COUNT; v_count:=v_count+v_rows;
INSERT INTO notifications(user_id,type,title,body,sweepstakes_id,source_reference,dedupe_key,priority,metadata)
SELECT us.user_id,CASE WHEN ce.field_name='end_at' THEN 'deadline_changed'::notification_type ELSE 'rules_changed'::notification_type END,'Saved opportunity changed',s.title||' changed. Review the sponsor-controlled official rules.',s.id,ce.id::text,'change:'||ce.id::text,80,jsonb_build_object('field',ce.field_name,'detectedAt',ce.detected_at)
FROM user_saved_sweepstakes us JOIN sweepstakes_change_events ce ON ce.sweepstakes_id=us.sweepstakes_id JOIN sweepstakes s ON s.id=ce.sweepstakes_id WHERE ce.detected_at>=p_now-interval '24 hours' ON CONFLICT DO NOTHING; GET DIAGNOSTICS v_rows=ROW_COUNT; v_count:=v_count+v_rows;
INSERT INTO notifications(user_id,type,title,body,sweepstakes_id,source_reference,dedupe_key,priority,metadata)
SELECT us.user_id,'opportunity_canceled','Saved opportunity canceled',s.title||' is marked canceled. Do not rely on prior listing details.',s.id,s.id::text,'canceled:'||s.id||':'||to_char(s.updated_at,'YYYY-MM-DD-HH24'),90,'{}'::jsonb FROM user_saved_sweepstakes us JOIN sweepstakes s ON s.id=us.sweepstakes_id WHERE s.status='canceled' AND s.updated_at>=p_now-interval '24 hours' ON CONFLICT DO NOTHING; GET DIAGNOSTICS v_rows=ROW_COUNT; v_count:=v_count+v_rows;
INSERT INTO notifications(user_id,type,title,body,sweepstakes_id,source_reference,dedupe_key,priority,metadata)
SELECT us.user_id,'source_confidence_reduced','Source confidence reduced',s.title||' now has reduced source confidence. Verify attribution and official rules.',s.id,s.id::text,'source-confidence:'||s.id||':'||to_char(s.last_verified_at,'YYYY-MM-DD-HH24'),75,jsonb_build_object('sourceConfidence',s.source_confidence_score) FROM user_saved_sweepstakes us JOIN sweepstakes s ON s.id=us.sweepstakes_id WHERE s.source_confidence_score<50 AND s.last_verified_at>=p_now-interval '24 hours' ON CONFLICT DO NOTHING; GET DIAGNOSTICS v_rows=ROW_COUNT; v_count:=v_count+v_rows;
INSERT INTO notifications(user_id,type,title,body,source_reference,dedupe_key,priority,metadata)
SELECT r.user_id,'custom_scan_completed','Custom scan completed',cs.name||' completed with '||r.match_count||' matching opportunities.',r.id::text,'custom-scan:'||r.id::text,50,jsonb_build_object('runId',r.id,'scannerId',r.custom_scanner_id,'matchCount',r.match_count) FROM custom_scan_runs r JOIN custom_scanners cs ON cs.id=r.custom_scanner_id WHERE r.status IN('completed','partial') AND r.completed_at>=p_now-interval '24 hours' ON CONFLICT DO NOTHING; GET DIAGNOSTICS v_rows=ROW_COUNT; v_count:=v_count+v_rows;
INSERT INTO notifications(user_id,type,title,body,source_reference,dedupe_key,priority,metadata)
SELECT b.user_id,'payment_failed','Subscription payment needs attention','Stripe reported a failed subscription payment. Review billing before the grace period ends.',b.provider_event_id,'payment:'||b.provider_event_id,100,'{}'::jsonb FROM billing_events b WHERE b.user_id IS NOT NULL AND b.event_type='invoice.payment_failed' AND b.status='processed' AND b.processed_at>=p_now-interval '7 days' ON CONFLICT DO NOTHING; GET DIAGNOSTICS v_rows=ROW_COUNT; v_count:=v_count+v_rows;
INSERT INTO notifications(user_id,type,title,body,source_reference,dedupe_key,priority,metadata)
SELECT p.id,'credits_low','Pilot Credits running low','Your Pilot Credit balance is below 20% of the included monthly grant.',to_char(p_now,'YYYY-MM'),'credits-low:'||to_char(p_now,'YYYY-MM'),60,jsonb_build_object('balance',pilot_credit_balance(p.id)) FROM profiles p LEFT JOIN subscriptions sub ON sub.user_id=p.id WHERE pilot_credit_balance(p.id)<CASE coalesce(sub.plan_key,'free_flight') WHEN 'squadron' THEN 400 WHEN 'ace_pilot' THEN 150 WHEN 'co_pilot' THEN 40 ELSE 2 END ON CONFLICT DO NOTHING; GET DIAGNOSTICS v_rows=ROW_COUNT; v_count:=v_count+v_rows;
RETURN v_count; END $$;

CREATE OR REPLACE FUNCTION claim_due_custom_scanners(p_now timestamptz DEFAULT now(),p_limit integer DEFAULT 10) RETURNS SETOF custom_scanners LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN RETURN QUERY WITH due AS(SELECT id FROM custom_scanners WHERE enabled AND next_run_at<=p_now ORDER BY next_run_at FOR UPDATE SKIP LOCKED LIMIT greatest(1,least(p_limit,50))),claimed AS(UPDATE custom_scanners c SET next_run_at=p_now+make_interval(mins=>c.cadence_minutes),last_run_at=p_now,updated_at=p_now FROM due WHERE c.id=due.id RETURNING c.*) SELECT * FROM claimed; END $$;

CREATE OR REPLACE FUNCTION count_custom_scan_matches(p_filters jsonb,p_source_ids uuid[]) RETURNS integer LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
SELECT count(DISTINCT s.id)::integer
FROM sweepstakes s
WHERE s.status='active'
  AND (s.end_at IS NULL OR s.end_at>now())
  AND EXISTS(SELECT 1 FROM sweepstakes_sources ss WHERE ss.sweepstakes_id=s.id AND ss.source_id=ANY(p_source_ids))
  AND (nullif(trim(p_filters->>'keywords'),'') IS NULL OR lower(s.title||' '||s.sponsor_name||' '||s.summary) LIKE '%'||lower(trim(p_filters->>'keywords'))||'%' OR EXISTS(SELECT 1 FROM sweepstakes_prizes sp WHERE sp.sweepstakes_id=s.id AND lower(sp.name||' '||coalesce(sp.description,'')) LIKE '%'||lower(trim(p_filters->>'keywords'))||'%'))
  AND (nullif(trim(p_filters->>'sponsor'),'') IS NULL OR lower(s.sponsor_name) LIKE '%'||lower(trim(p_filters->>'sponsor'))||'%')
  AND (NOT (p_filters?'minimumValue') OR s.estimated_total_prize_value>=((p_filters->>'minimumValue')::numeric))
  AND (NOT (p_filters?'maximumEffort') OR s.entry_effort_score<=((p_filters->>'maximumEffort')::integer))
  AND (NOT (p_filters?'deadlineBefore') OR s.end_at<=((p_filters->>'deadlineBefore')::timestamptz))
  AND (nullif(trim(p_filters->>'country'),'') IS NULL OR EXISTS(SELECT 1 FROM sweepstakes_eligibility se WHERE se.sweepstakes_id=s.id AND (cardinality(se.eligible_countries)=0 OR upper(trim(p_filters->>'country'))=ANY(se.eligible_countries))))
  AND (nullif(trim(p_filters->>'region'),'') IS NULL OR EXISTS(SELECT 1 FROM sweepstakes_eligibility se WHERE se.sweepstakes_id=s.id AND upper(trim(p_filters->>'region'))=ANY(se.eligible_regions) AND NOT upper(trim(p_filters->>'region'))=ANY(se.excluded_regions)))
  AND (nullif(trim(coalesce(p_filters->>'category',p_filters->>'prizeType')),'') IS NULL OR EXISTS(SELECT 1 FROM sweepstakes_category_links scl JOIN sweepstakes_categories sc ON sc.id=scl.category_id WHERE scl.sweepstakes_id=s.id AND (lower(sc.slug)=lower(trim(coalesce(p_filters->>'category',p_filters->>'prizeType'))) OR lower(sc.name) LIKE '%'||lower(trim(coalesce(p_filters->>'category',p_filters->>'prizeType')))||'%')) OR EXISTS(SELECT 1 FROM sweepstakes_prizes sp WHERE sp.sweepstakes_id=s.id AND lower(sp.name) LIKE '%'||lower(trim(coalesce(p_filters->>'category',p_filters->>'prizeType')))||'%'));
$$;
REVOKE ALL ON FUNCTION generate_phase9_notifications(timestamptz),claim_due_custom_scanners(timestamptz,integer),count_custom_scan_matches(jsonb,uuid[]) FROM PUBLIC;
DO $$ BEGIN IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='service_role') THEN GRANT SELECT,INSERT,UPDATE,DELETE ON notification_preferences,notifications,notification_deliveries,digest_runs,custom_scanners,custom_scan_runs TO service_role; GRANT EXECUTE ON FUNCTION generate_phase9_notifications(timestamptz),claim_due_custom_scanners(timestamptz,integer),count_custom_scan_matches(jsonb,uuid[]) TO service_role; END IF; END $$;
