-- Phase 10 is additive. Administrative actions are server-authorized, durable, and auditable.
CREATE TYPE support_request_status AS ENUM ('open','reviewing','resolved','closed');
CREATE TYPE support_request_priority AS ENUM ('low','normal','high','urgent');

CREATE TABLE admin_audit_logs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),actor_user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE RESTRICT,actor_role text NOT NULL CHECK(actor_role IN('admin','owner')),action text NOT NULL,target_type text NOT NULL,target_id text NOT NULL,before_state jsonb,after_state jsonb,reason text NOT NULL CHECK(char_length(trim(reason)) BETWEEN 3 AND 1000),correlation_id text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX admin_audit_logs_created_idx ON admin_audit_logs(created_at DESC);
CREATE INDEX admin_audit_logs_target_idx ON admin_audit_logs(target_type,target_id,created_at DESC);
CREATE TABLE feature_flags(key text PRIMARY KEY CHECK(key ~ '^[a-z][a-z0-9_.-]{2,79}$'),enabled boolean NOT NULL DEFAULT false,description text NOT NULL DEFAULT '',metadata jsonb NOT NULL DEFAULT '{}'::jsonb,updated_by uuid REFERENCES profiles(id) ON DELETE SET NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE support_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE RESTRICT,subject text NOT NULL,message text NOT NULL,status support_request_status NOT NULL DEFAULT 'open',priority support_request_priority NOT NULL DEFAULT 'normal',assigned_to uuid REFERENCES profiles(id) ON DELETE SET NULL,resolution text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX support_requests_status_idx ON support_requests(status,priority,created_at);
CREATE TABLE application_errors(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),correlation_id text NOT NULL,route text NOT NULL,method text NOT NULL,error_name text NOT NULL,safe_message text NOT NULL,metadata jsonb NOT NULL DEFAULT '{}'::jsonb,occurred_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX application_errors_occurred_idx ON application_errors(occurred_at DESC);

ALTER TABLE admin_audit_logs ENABLE ROW LEVEL SECURITY; ALTER TABLE feature_flags ENABLE ROW LEVEL SECURITY; ALTER TABLE support_requests ENABLE ROW LEVEL SECURITY; ALTER TABLE application_errors ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON admin_audit_logs,feature_flags,support_requests,application_errors FROM authenticated,anon;

CREATE OR REPLACE FUNCTION prevent_admin_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'ADMIN_AUDIT_LOG_IS_APPEND_ONLY'; END $$;
CREATE TRIGGER admin_audit_logs_immutable BEFORE UPDATE OR DELETE ON admin_audit_logs FOR EACH ROW EXECUTE FUNCTION prevent_admin_audit_mutation();

ALTER TABLE credit_ledger DROP CONSTRAINT credit_ledger_type_sign;
ALTER TABLE credit_ledger ADD CONSTRAINT credit_ledger_type_sign CHECK ((entry_type='consume' AND amount<0) OR (entry_type IN('grant','refund') AND amount>0) OR (entry_type='adjustment' AND amount<>0));
CREATE OR REPLACE FUNCTION adjust_pilot_credits(p_user_id uuid,p_amount integer,p_reason_code text,p_source_reference text,p_idempotency_key text,p_metadata jsonb DEFAULT '{}'::jsonb) RETURNS TABLE(entry_id uuid,balance bigint,applied boolean) LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE v_id uuid; v_balance bigint; BEGIN IF p_amount=0 OR abs(p_amount)>100000 THEN RAISE EXCEPTION 'INVALID_CREDIT_ADJUSTMENT'; END IF; PERFORM pg_advisory_xact_lock(hashtextextended(p_user_id::text,0)); SELECT id INTO v_id FROM credit_ledger WHERE idempotency_key=p_idempotency_key AND user_id=p_user_id; IF v_id IS NOT NULL THEN RETURN QUERY SELECT v_id,pilot_credit_balance(p_user_id),false; RETURN; END IF; v_balance:=pilot_credit_balance(p_user_id); IF v_balance+p_amount<0 THEN RAISE EXCEPTION 'ADJUSTMENT_WOULD_CREATE_NEGATIVE_BALANCE'; END IF; INSERT INTO credit_ledger(user_id,amount,entry_type,reason_code,source_reference,idempotency_key,metadata) VALUES(p_user_id,p_amount,'adjustment',p_reason_code,p_source_reference,p_idempotency_key,p_metadata) RETURNING id INTO v_id; RETURN QUERY SELECT v_id,pilot_credit_balance(p_user_id),true; END $$;

CREATE OR REPLACE FUNCTION admin_merge_sweepstakes(p_target_id uuid,p_source_id uuid,p_actor_id uuid,p_reason text) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE v_event_id uuid; v_target jsonb; v_source jsonb; v_links jsonb; BEGIN IF p_target_id=p_source_id THEN RAISE EXCEPTION 'MERGE_IDS_MUST_DIFFER'; END IF; SELECT to_jsonb(s) INTO v_target FROM sweepstakes s WHERE id=p_target_id FOR UPDATE; SELECT to_jsonb(s) INTO v_source FROM sweepstakes s WHERE id=p_source_id FOR UPDATE; IF v_target IS NULL OR v_source IS NULL THEN RAISE EXCEPTION 'MERGE_LISTING_NOT_FOUND'; END IF; SELECT coalesce(jsonb_agg(to_jsonb(ss)),'[]'::jsonb) INTO v_links FROM sweepstakes_sources ss WHERE sweepstakes_id=p_source_id; INSERT INTO sweepstakes_sources(sweepstakes_id,source_id,discovered_url_id,source_listing_title,source_listing_text,first_seen_at,last_seen_at) SELECT p_target_id,source_id,discovered_url_id,source_listing_title,source_listing_text,first_seen_at,last_seen_at FROM sweepstakes_sources WHERE sweepstakes_id=p_source_id ON CONFLICT DO NOTHING; DELETE FROM sweepstakes_sources WHERE sweepstakes_id=p_source_id; UPDATE sweepstakes SET status='unverifiable',summary='Merged duplicate of '||p_target_id::text,updated_at=now() WHERE id=p_source_id; INSERT INTO sweepstakes_merge_events(target_sweepstakes_id,source_sweepstakes_id,match_score,matched_signals,source_snapshot,status,merged_by) VALUES(p_target_id,p_source_id,1,jsonb_build_object('manual',true),jsonb_build_object('targetBefore',v_target,'sourceBefore',v_source,'sourceLinks',v_links,'reason',p_reason),'applied',p_actor_id) RETURNING id INTO v_event_id; RETURN v_event_id; END $$;

CREATE OR REPLACE FUNCTION admin_undo_merge(p_event_id uuid,p_actor_id uuid) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE v_event sweepstakes_merge_events%ROWTYPE; v_target jsonb; v_source jsonb; v_link jsonb; BEGIN SELECT * INTO v_event FROM sweepstakes_merge_events WHERE id=p_event_id AND status='applied' FOR UPDATE; IF NOT FOUND THEN RAISE EXCEPTION 'APPLIED_MERGE_NOT_FOUND'; END IF; v_target:=v_event.source_snapshot->'targetBefore'; v_source:=v_event.source_snapshot->'sourceBefore'; UPDATE sweepstakes SET title=v_target->>'title',normalized_title=v_target->>'normalized_title',sponsor_name=v_target->>'sponsor_name',summary=coalesce(v_target->>'summary',''),official_url=v_target->>'official_url',rules_url=v_target->>'rules_url',start_at=(v_target->>'start_at')::timestamptz,end_at=(v_target->>'end_at')::timestamptz,status=(v_target->>'status')::sweepstakes_lifecycle_status,updated_at=now() WHERE id=v_event.target_sweepstakes_id; IF v_event.source_sweepstakes_id IS NOT NULL AND v_source IS NOT NULL THEN UPDATE sweepstakes SET title=v_source->>'title',normalized_title=v_source->>'normalized_title',sponsor_name=v_source->>'sponsor_name',summary=coalesce(v_source->>'summary',''),official_url=v_source->>'official_url',rules_url=v_source->>'rules_url',start_at=(v_source->>'start_at')::timestamptz,end_at=(v_source->>'end_at')::timestamptz,status=(v_source->>'status')::sweepstakes_lifecycle_status,updated_at=now() WHERE id=v_event.source_sweepstakes_id; FOR v_link IN SELECT * FROM jsonb_array_elements(coalesce(v_event.source_snapshot->'sourceLinks','[]'::jsonb)) LOOP DELETE FROM sweepstakes_sources WHERE sweepstakes_id=v_event.target_sweepstakes_id AND source_id=(v_link->>'source_id')::uuid AND discovered_url_id=(v_link->>'discovered_url_id')::uuid; INSERT INTO sweepstakes_sources(sweepstakes_id,source_id,discovered_url_id,source_listing_title,source_listing_text,first_seen_at,last_seen_at) VALUES(v_event.source_sweepstakes_id,(v_link->>'source_id')::uuid,(v_link->>'discovered_url_id')::uuid,v_link->>'source_listing_title',v_link->>'source_listing_text',(v_link->>'first_seen_at')::timestamptz,(v_link->>'last_seen_at')::timestamptz) ON CONFLICT DO NOTHING; END LOOP; END IF; UPDATE sweepstakes_merge_events SET status='undone',undone_by=p_actor_id,undone_at=now() WHERE id=p_event_id; RETURN v_event.target_sweepstakes_id; END $$;

REVOKE ALL ON FUNCTION adjust_pilot_credits(uuid,integer,text,text,text,jsonb),admin_merge_sweepstakes(uuid,uuid,uuid,text),admin_undo_merge(uuid,uuid) FROM PUBLIC;
DO $$ BEGIN IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='service_role') THEN GRANT SELECT,INSERT,UPDATE,DELETE ON feature_flags,support_requests,application_errors TO service_role; GRANT SELECT,INSERT ON admin_audit_logs TO service_role; GRANT EXECUTE ON FUNCTION adjust_pilot_credits(uuid,integer,text,text,text,jsonb),admin_merge_sweepstakes(uuid,uuid,uuid,text),admin_undo_merge(uuid,uuid) TO service_role; END IF; END $$;
